### ISSUE TITLE
Fake points appear face down in score areas

### ISSUE THREAD

**Issue by kalotay** [mtgred/netrunner#6117] opened 2021-11-01 17:39 UTC
Fake points (e.g. Mad Dash, Gene Splicer) appear facedown in score areas.
<img width="135" alt="Screenshot 2021-11-01 at 18 01 47" src="https://user-images.githubusercontent.com/661871/139715373-ac843fa3-ff78-48ce-89f3-e5fa004bf988.png">
.

**Comment by mikeprosser** [comment] 2021-11-02 13:00
Aah whoops, I raised a duplicate of this here https://github.com/mtgred/netrunner/issues/6119 which I've now closed. As I commented in there, Eavesdrop also seems to be installing face down on unrezzed ice - although that might be a different issue as the fake points still "work", Eavesdrop encounter doesn't trigger

**Comment by NoahTheDuke** [comment] 2021-11-02 19:03
Thanks for the report!

**Closed** 2021-11-04 16:48 UTC
Labels: bug, game interface, engine
