### ISSUE TITLE
Azmari EdTech: Shaping the Future - Make it Blocking

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#3146] opened 2018-03-05 21:03 UTC
Currently, Corp ends their turn and is prompted for card type selection. The runner is able to start their turn and play cards before corp has selected card type.

The selection prompt should block runner start of turn so the runner can't play cards before corp has selected.

**Comment by nealterrell** [comment] 2018-03-05 23:08
Duplicate of #3142. Thanks!

**Closed by nealterrell** 2018-03-05 23:08 UTC

**Comment by tblackwe** [comment] 2018-03-05 23:36
Thanks! I was blind and missed it entirely

**Comment by nealterrell** [comment] 2018-03-05 23:37
We'd rather have the extra report than nothing at all :).
