### ISSUE TITLE
Davinci makes the game "freeze"

### ISSUE THREAD

**Issue by Grimstringer** [mtgred/netrunner#1196] opened 2016-02-07 15:21 UTC
2 times in two games my opponent used one time  maker's eye and the next one Dirty laundry and Davinci made the game freeze, he couldnt do anything or me so we just quit. 

no counters on it, no access, nothing

**Comment by bmatsuo** [comment] 2016-02-08 04:22
This sounds like it may be the same as #1199. Do you think so, @domtancredi?

**Comment by domtancredi** [comment] 2016-02-08 06:17
Program with counters but non virus? Sounds like the same issue exactly.

This PR should fix it (will need to test)

**Comment by bmatsuo** [comment] 2016-02-08 06:31
I replicated this problem running on an empty Archives with a newly installed DaVinci. The root cause appears to be the same as #1199.

**Comment by domtancredi** [comment] 2016-02-08 14:52
@Grimstringer The fix has been merged. Would you test and close the issue if it passes?

**Closed** 2016-02-10 17:01 UTC
Labels: bug
