### ISSUE TITLE
Gang Sign causes game-ending bug

### ISSUE THREAD

**Issue by NotTopGearRH** [mtgred/netrunner#806] opened 2015-10-11 23:48 UTC
IF a player with multiple Gang Signs in place has them trigger, all instances of gang sign check the opponents hand simultaneously.  If the first instance to resolve finds an agenda, and it is stolen, if other instances of gang sign find the same agenda, you are prompted to steal the agenda which you have already stolen, and you cannot advance the board state.

Multiple Gang signs need to fire sequentially, not simultaneously, as this allows players to use trash effects to take cards from hand or steal agendas from hand before the second instance of gang sign checks the now reduced hand.

**Comment by JoelCFC25** [comment] 2015-10-12 02:17
Thanks for the report. This is a duplicate of #519. Properly sequencing multiple effects like this is one of the biggest outstanding problems to solve.

**Comment by beamdogcody** [comment] 2015-10-20 17:15
Could do like Fisk and have Gang Signs fire manually

**Comment by JoelCFC25** [comment] 2015-11-15 18:26
Fixed by #855.

**Closed by JoelCFC25** 2015-11-15 18:26 UTC
Labels: duplicate
