### ISSUE TITLE
Public agendas showing facedown

### ISSUE THREAD

**Issue by Dirjel** [mtgred/netrunner#6536] opened 2022-08-13 01:18 UTC
When Corp installs a public agenda (tested with Oaktown Renovations and City Works Project), it appears facedown in the remote server, but the name does show in the game log.

They do appear face up for the corp player, but the Runner player cannot see them.

**Comment by francescopellegrini** [comment] 2022-08-24 19:39
Yesterday I experienced an even worse regression: the public agenda appeared facedown for the Corp as well! 😱

**Comment by francescopellegrini** [comment] 2022-08-24 20:11
Also duplicate of #6496

**Comment by jaimefps** [comment] 2022-08-27 08:17
Had the same issue today

**Comment by jespo655** [comment] 2022-08-30 23:09
I've been playing Oaktown Renovation lately, and this happens every game. It's pretty annoying

**Comment by NoahTheDuke** [comment] 2022-08-31 03:51
Fixed as of #6578

**Closed by NoahTheDuke** 2022-08-31 03:51 UTC
