### ISSUE TITLE
Corp cannot trigger Media Blitz for a runner stolen Hades Fragment

### ISSUE THREAD

**Issue by dlthorpe** [mtgred/netrunner#1397] opened 2016-03-27 13:01 UTC
So the runner has stolen the Hades Fragment.  The Corp plays Medis Blitz to gain the text of that agenda.  The Corp now wants to trigger it at the start of their turn.  There doesn't seem to be a way to do this by clicking the stolen agenda or the Media Blitz current. 

I think the best place should be the current.

**Comment by zaroth** [comment] 2016-03-27 13:03
Duplicate of #900, Media Blitz is not implemented.

**Closed by zaroth** 2016-03-27 13:03 UTC
