### ISSUE TITLE
Comet and run events

### ISSUE THREAD

**Issue by unitled** [mtgred/netrunner#691] opened 2015-09-08 14:53 UTC
Comet asks if you want to play a free event as soon as you've used the previous event. It should wait until the event is resolved before it does this. This means a run event lets you play another run event right before the first one starts. It's not a big issue as you can manually take the click and play the event once you've finished your run!

**Comment by JoelCFC25** [comment] 2015-09-08 14:57
Duplicate of #322.

**Comment by JoelCFC25** [comment] 2015-11-15 18:27
Fixed by #854.

**Closed by JoelCFC25** 2015-11-15 18:27 UTC
Labels: bug, duplicate
