### ISSUE TITLE
When undoing a card play, it should be put back into your hand

### ISSUE THREAD

**Issue by DDarkray** [mtgred/netrunner#6251] opened 2022-02-14 19:32 UTC
Whenever you use undo-click to undo a card play (such as Overclock), I think it should be put back into your hand by default (without having to manually drag it back to your hand).

**Comment by francescopellegrini** [comment] 2022-02-14 19:42
Duplicate of #5362

**Comment by francescopellegrini** [comment] 2023-01-02 15:36
Might as well close this.

**Comment by francescopellegrini** [comment] 2023-10-08 12:53
@NoahTheDuke fixed already.

**Closed** 2023-10-08 14:32 UTC
