### ISSUE TITLE
Multiple server with same rezzed cards

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#1458] opened 2016-04-20 12:23 UTC
To reduce a little the inconvenient of mandatory zoom out when playing against horizontal deck (like IG, Gagarin, NBN Server Spam) it would be nice if is possible stacking server with the same card installed and no other cards in the server (upgrade, ice).

ex: 3 PAD campaign with no ice or upgrade.

We do it in real life so I think is nice to have it also in Jinteki.
Maybe it can be an option for the corp to ask and  the runner can accept or decline.

I've some UI idea if needed.

**Comment by zaroth** [comment] 2016-04-20 13:16
Duplicate of #1279. See also #1210, #512 and #1383.

**Closed by zaroth** 2016-04-20 13:16 UTC
