### ISSUE TITLE
game freezing on street peddler trash

### ISSUE THREAD

**Issue by stimmyrobbins** [mtgred/netrunner#2000] opened 2016-09-25 16:54 UTC
menu for peddler is displayed but then hosted cards cannot be installed or any other action including chat cannot be performed

**Comment by JoelCFC25** [comment] 2016-09-25 18:12
We will need more details. Was the Peddler hosted (e.g., on Off-Campus Apartment?). What were you attempting to install?

**Comment by stimmyrobbins** [comment] 2016-09-25 18:22
Yes sorry forgot to mention that was hosted on off campus.  I don't
remember what was in the cue.  Can I submit a screenshot to the github? If
so I will do that next time.  I think it was spy camera street peddler and
spike in the street peddler menu.

**Comment by nealterrell** [comment] 2016-09-26 00:42
Yep, screenshots can be attached. If you use a tool like Snipping Tool (Windows) or similar to copy a screenshot to the clipboard, you can then just "paste" it directly into a comment box on GitHub.

**Comment by erbridge** [comment] 2016-09-26 00:59
Perhaps this is related to #1993? Though the fix in #1994 only affects corp cards, though.

**Comment by nealterrell** [comment] 2016-09-26 02:15
This is a duplicate of #1896, which has been open for some time without a reproducible test case.

**Comment by stimmyrobbins** [comment] 2016-09-26 02:16
I will try to reproduce this later tonight with more stats.

**Comment by stimmyrobbins** [comment] 2016-09-26 17:40
I played a game last night but the game did not crash.  It was very late
though around 3 am eastern when there aren't a lot of games.  I notice that
the issue arose mostly during the day maybe when the load was higher.  I
play the deck every day so I will notify of any issue.

**Comment by stimmyrobbins** [comment] 2016-09-26 17:42
Also I wanted to ask if there are other open issues that can't be
reproduced.  Maybe I could help out?

**Comment by Saintis** [comment] 2016-09-26 17:44
Issues with the "can't reproduce" label can be found [here](https://github.com/mtgred/netrunner/labels/can%27t%20reproduce).

I also now strongly believe all these issues are due to heavy load on the server and hence multiple commands being sent / processed without the state updated in between.

**Comment by stimmyrobbins** [comment] 2016-09-26 17:59
I will look at the link thank you.  I think it is a load issue as well.

On Sep 26, 2016 1:44 PM, "Filip Gokstorp" <notifications@github.com> wrote:

Issues with the "can't reproduce" label can be found here
<https://github.com/mtgred/netrunner/labels/can%27t%20reproduce>.

I also now strongly believe all these issues are due to heavy load on the
server and hence multiple commands being sent / processed without the state
updated in between.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mtgred/netrunner/issues/2000#issuecomment-249642498>,
or mute the thread

**Comment by stimmyrobbins** [comment] 2016-09-28 03:44
Hi All,

I just experienced the same freezing.  Please see screenshot.

**Comment by Saintis** [comment] 2016-09-28 08:57
Seems like the screenshot did not work properly in the email reply. Try adding it via the web instead.

Also, do you remember how many games were on when the freeze happened?

**Comment by stimmyrobbins** [comment] 2016-10-16 03:18
Not sure why you couldn't see screen cap but the crash happens in the
following order every time.

Off campus install
Peddler host
Peddler on peddler
Trash to install peddler
Crash

**Comment by JoelCFC25** [comment] 2016-10-16 19:23
Thanks for the set of steps--unfortunately I *still* can't reproduce this.

**Comment by JoelCFC25** [comment] 2016-11-30 16:05
```Error  do choice Spy Camera #error {
 :cause Key must be integer
 :via
 [{:type java.lang.IllegalArgumentException
   :message Key must be integer
   :at [clojure.lang.APersistentVector assoc APersistentVector.java 345]}]
 :trace
 [[clojure.lang.APersistentVector assoc APersistentVector.java 345]
  [clojure.lang.APersistentVector assoc APersistentVector.java 18]
  [clojure.lang.RT assoc RT.java 792]
  [clojure.core$assoc__4371 invokeStatic core.clj 191]
  [clojure.core$update_in invokeStatic core.clj 5950]
  [clojure.core$update_in doInvoke core.clj 5939]
  [clojure.lang.RestFn invoke RestFn.java 445]
  [clojure.lang.AFn applyToHelper AFn.java 160]
  [clojure.lang.RestFn applyTo RestFn.java 132]
  [clojure.core$apply invokeStatic core.clj 652]
  [clojure.core$update_in invokeStatic core.clj 5949]
  [clojure.core$update_in doInvoke core.clj 5939]
  [clojure.lang.RestFn invoke RestFn.java 445]
  [clojure.lang.Atom swap Atom.java 65]
  [clojure.core$swap_BANG_ invokeStatic core.clj 2262]
  [clojure.core$swap_BANG_ invoke core.clj 2253]
  [game.core$show_prompt invokeStatic abilities.clj 338]
  [game.core$show_prompt invoke abilities.clj 314]
  [game.core$show_prompt invokeStatic abilities.clj 318]
  [game.core$show_prompt invoke abilities.clj 314]
  [game.core$show_wait_prompt invokeStatic abilities.clj 390]
  [game.core$show_wait_prompt invoke abilities.clj 384]
  [game.core$trigger_event_simult$fn__3928 invoke events.clj 179]
  [game.core$effect_completed invokeStatic events.clj 240]
  [game.core$effect_completed invoke events.clj 236]
  [game.core$resolve_ability_eid invokeStatic abilities.clj 116]
  [game.core$resolve_ability_eid invoke abilities.clj 113]
  [game.core$resolve_ability invokeStatic abilities.clj 111]
  [game.core$resolve_ability invoke abilities.clj 38]
  [game.core$trigger_event_simult invokeStatic events.clj 177]
  [game.core$trigger_event_simult doInvoke events.clj 139]
  [clojure.lang.RestFn invoke RestFn.java 533]
  [game.core$runner_install invokeStatic installing.clj 330]
  [game.core$runner_install invoke installing.clj 297]
  [game.core$runner_install invokeStatic installing.clj 300]
  [game.core$runner_install invoke installing.clj 297]
  [game.core$fn__23480 invokeStatic resources.clj 1121]
  [game.core$fn__23480 invoke resources.clj 1114]
  [game.core$do_effect invokeStatic abilities.clj 260]
  [game.core$do_effect invoke abilities.clj 256]
  [game.core$do_ability invokeStatic abilities.clj 241]
  [game.core$do_ability invoke abilities.clj 214]
  [game.core$resolve_ability_eid invokeStatic abilities.clj 136]
  [game.core$resolve_ability_eid invoke abilities.clj 113]
  [game.core$resolve_ability invokeStatic abilities.clj 111]
  [game.core$resolve_ability invoke abilities.clj 38]
  [game.core$resolve_ability invokeStatic abilities.clj 109]
  [game.core$resolve_ability invoke abilities.clj 38]
  [game.core$prompt_BANG_$fn__4734 invoke abilities.clj 309]
  [game.core$resolve_prompt invokeStatic actions.clj 143]
  [game.core$resolve_prompt invoke actions.clj 113]
  [game.main$handle_do invokeStatic main.clj 77]
  [game.main$handle_do invoke main.clj 74]
  [game.main$handle_command invokeStatic main.clj 150]
  [game.main$handle_command invoke main.clj 139]
  [game.main$run$fn__25627 invoke main.clj 185]
  [game.main$run invokeStatic main.clj 175]
  [game.main$run invoke main.clj 169]
  [game.main$dev invokeStatic main.clj 222]
  [game.main$dev invoke main.clj 218]
  [clojure.core$binding_conveyor_fn$fn__4676 invoke core.clj 1938]
  [clojure.lang.AFn call AFn.java 18]
  [java.util.concurrent.FutureTask run FutureTask.java 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}```

Finally reproduced. Steps are as follows: 

1. Install Off-Campus Apartment
2. Install and host a Street Peddler on it, ensuring that another Street Peddler is one of the facedown cards
3. Trash the original Peddler to install the facedown Peddler it hosts
4. Retroactively host the new Peddler (and its 3 facedown cards, one of which is Spy Camera) on OCA
5. Click the new Peddler to trash it and try choosing Spy Camera from the choices prompt--the game freezes, but without a red error popup

**Comment by stimmyrobbins** [comment] 2016-11-30 16:20
Happy you were able to reproduce it.  Hope it's an easy fix.  Let me know
if you need me to test this scenario if a fix is implemented.

**Comment by nealterrell** [comment] 2016-12-29 23:14
Thanks @JoelCFC25 for the steps to reproduce. Turns out it was Off-Campus Apartment's "Host an installed card" ability; selecting a card that itself was hosting cards broke the nested hosting.

**Closed** 2017-01-02 02:33 UTC
Labels: bug, cards

**Comment by stimmyrobbins** [comment] 2017-01-03 20:35
Hey Minh happy New year.  as thanks for helping with this do you think you
could code ver sltr.  it sounds fun in geist.  :p.  let me know.
