### ISSUE TITLE
Obelus on successful run with Counter Surveillance drew X cards.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2691] opened 2017-08-07 17:27 UTC
Had Obelus installed. Then made a counter surveillance on R&D and the drew was instantaneous instead of one by one as the access happens.

**Comment by danhut** [comment] 2017-08-08 01:17
Duplicate of https://github.com/mtgred/netrunner/issues/2675
Can you please close this?

**Closed** 2017-08-10 05:05 UTC
