### ISSUE TITLE
Move "you have start of turn triggers" reminder pop-up to "Start Turn" button

### ISSUE THREAD

**Issue by Dirjel** [mtgred/netrunner#5747] opened 2021-04-02 18:48 UTC
It would be much easier to notice the "you have start of turn triggers" popup (e.g. beginning turn with unrezzed Nico Campaign) if it was right next to the "Start Turn" button instead of in the very top right corner of the screen.

**Comment by NoahTheDuke** [comment] 2021-04-02 19:26
Duplicate of #5727.

**Closed by NoahTheDuke** 2021-04-02 19:26 UTC
Labels: duplicate, enhancement, game interface
