### ISSUE TITLE
Exclusive Party still locks up the whole game

### ISSUE THREAD

**Issue by JeffMol** [mtgred/netrunner#4131] opened 2019-03-20 16:08 UTC
Not sure why this issue was closed because it's still happening.  When I click Exclusive Party to play it, it takes several seconds, then moves to a temporary zone and draws a card.  Then everything but chat locks up.  Clicking or dragging anything else does nothing.  Undoing the click gives me the click back and puts the drawn card back in the stack, but EP stays in the temporary zone and everything stays locked up.  I am unsure of whether or not EP is also having trouble gaining credits because I've obviously never played a second one.

**Comment by NoahTheDuke** [comment] 2019-03-20 16:12
Duplicate of #4089   Thanks for the report!

**Closed** 2019-03-20 18:01 UTC
Labels: bug, cards, duplicate
