### ISSUE TITLE
(feature): new way to see cards left in deck

### ISSUE THREAD

**Issue by jaimefps** [mtgred/netrunner#7806] opened 2024-10-09 03:59 UTC
Feature request:

As a player on jnet, it would be super nice to have a way of seeing what cards are left in your deck, but without knowing the order they are in; instead of having to look through archives and reverse calculate the cards that are left. Maybe it would be "too helpful" in games, but I find it very useful when playing Keyforge in the web client. They allow you to see cards left in the deck.

If it is deemed too good for tournament play, maybe it can be set as a toggle option in the game lobby settings, maybe disabled by default so that in tournaments players have more friction when making decisions, if that's something that we want.

**Comment by NBKelly** [comment] 2024-10-09 06:05
Closed as duplicate of  #7779

**Closed by NBKelly** 2024-10-09 06:05 UTC
