### ISSUE TITLE
Recon drone offers prevent damage option when cards are not being accessed by the runner

### ISSUE THREAD

**Issue by willybn1** [mtgred/netrunner#6403] opened 2022-06-25 14:15 UTC
![image](https://user-images.githubusercontent.com/36125436/175777434-7f3c9635-ea4a-4f34-83ec-f58dad473b94.png)

**Comment by NoahTheDuke** [comment] 2022-06-25 14:37
Thanks for the report! Love your enthusiasm for Recon Drone but let's keep opinions out of the bug report lmao

**Comment by francescopellegrini** [comment] 2022-06-30 06:30
Duplicate of #5874

**Closed** 2022-09-07 00:25 UTC
Labels: bug, card
