### ISSUE TITLE
Log: Holo Man paid ability doesn't list the click + credit cost

### ISSUE THREAD

**Issue by webbedspace** [mtgred/netrunner#7488] opened 2024-06-27 13:26 UTC
![image](https://github.com/mtgred/netrunner/assets/83939/fba736e0-065d-4c2f-a3e8-0281b0af385e)
See image. Should say that the player "spends 4c and {click} to use The Holo Man to"

**Comment by NBKelly** [comment] 2024-06-27 18:52
Duplicate of #7394

**Closed** 2024-06-29 12:21 UTC
Labels: duplicate
