### ISSUE TITLE
Legwork run shows 'Runner accesses OK' as additional log

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#1325] opened 2016-03-09 17:36 UTC
Legwork run from Geist, chat says
runner accesses Enigma
runner accesses Assassin
Runner accesses OK.
Runner accesses Adonis Campaign.

**Comment by tolaasin** [comment] 2016-03-09 17:36
4 cards in HQ at the time

**Comment by JoelCFC25** [comment] 2016-03-09 18:28
Thanks for the report. We have this in already at #1247.

**Comment by tolaasin** [comment] 2016-03-09 21:17
Ok. I did search for legwork in the issues list first and it didn't come up.

**Comment by JoelCFC25** [comment] 2016-03-09 22:10
Yeah sorry, I forgot that the earlier one wasn't specific to Legwork, but the root cause I think is the same--multi-access of HQ. I'm hoping both of these will be taken care of by #1328.

**Comment by JoelCFC25** [comment] 2016-03-18 14:24
I am pretty confident this is fixed now, but please report it if you see it again!

**Closed** 2016-03-23 01:51 UTC
Labels: bug, duplicate

**Comment by zaroth** [comment] 2016-09-06 04:53
Main issue in #1662.
