### ISSUE TITLE
Levy turned me into Corp

### ISSUE THREAD

**Issue by cdrock** [mtgred/netrunner#74] opened 2015-01-22 01:40 UTC
I used LEVY and I was turned into the corporation.  My ID turned into my opponents ID, my heap was turned into Archives, etc.  It also removed all installed cards from the game.

**Comment by anathomical** [comment] 2015-01-30 23:30
I have been unable to reproduce this one across multiple attempts.  Possibly this was some weird one-off occurrence?

**Comment by eah13** [comment] 2015-05-19 11:25
@cdrock has this happened again?  If not, perhaps we can close this issue for now?

**Comment by JoelCFC25** [comment] 2015-08-05 14:17
Closing this. Reopen a new issue if it comes back and you can reliably reproduce it!

**Closed by JoelCFC25** 2015-08-05 14:17 UTC
Labels: can't reproduce
