### ISSUE TITLE
Accelerated Beta Test draws five cards instead of three

### ISSUE THREAD

**Issue by shizusreq** [mtgred/netrunner#1268] opened 2016-02-22 14:54 UTC
Hi,
I had a game where the **second** scored ABT allowed the Corp player to choose between five cards instead of three. The first time ABT was scored it worked correctly, drawing only three cards.

**Comment by JoelCFC25** [comment] 2016-02-22 15:38
Do you remember how many of the 3 cards from the first one were installed? If it was fewer than all 3, did the Corp player remember to trash the remaining card(s)? Basically, are you sure the Temporary Zone was emptied out in between the end of the first ABT score and the score of the second one?

Not able to reproduce this yet, but maybe there is something weird about the conditions in which this occurred.

**Comment by shizusreq** [comment] 2016-02-22 15:46
It might have been a single card, but I believe the other cards were trashed. I will confirm with the Corp player and post here. Does the Temporary Zone become hidden even if there are cards still in it?

**Comment by JoelCFC25** [comment] 2016-02-22 15:49
No, as the Runner you should see Corp card backs in the Temporary Zone immediately after they decide to fire ABT, and you'll continue to see however many are left after they're done doing installs.

**Comment by shizusreq** [comment] 2016-02-22 15:55
Cool, confirmed that the cards were trashed correctly. Also, the Temporary Zone disappeared after the first time ABT was scored and the cards were trashed.

**Comment by JoelCFC25** [comment] 2016-03-18 14:25
Any more sightings of this one?

**Comment by shizusreq** [comment] 2016-03-18 14:49
Nope, but will post if it happens to pop up. Would including the chat history or screenshots help?

**Comment by queueseven** [comment] 2016-04-13 19:19
Since we can't reproduce this, I'm going to close this issue. If it happens again, feel free to drop a note. Chat history and screenshot would also be great.

**Closed by queueseven** 2016-04-13 19:19 UTC
Labels: bug, can't reproduce, cards
