### ISSUE TITLE
Game with Space-Ice and Femme Fatale crashed. Weird behavior.

### ISSUE THREAD

**Issue by yojimbosteel** [mtgred/netrunner#2034] opened 2016-10-02 20:01 UTC
Weird behavior started when I installed Femmme Fatale mid-run with Personal Workshop. I removed the 8 remaining counters off of fem to target an Asteroid Belt (HQ, only ice) with 3 advancements on it. After this I noticed that there was no option to bypass and HQ seemed to be firing subs automatically. I finally received a red pop-up error when I attempted to use fem to break a Nebula on R&D (it might have been after just matching strength, I can't remember). 

Best of luck!

Stack Trace:

``` clojure
Error do auto-pump Femme Fatale #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at nil}]
 :trace
 []}
```

**Comment by JoelCFC25** [comment] 2016-10-07 16:28
Could be one of those weird instances that can't be reproduced, maybe involving lag. I tried what I understood to be your scenario just now and got no errors: 

1. Host Femme on PW
2. Run a server stacked with Asteroid Belt and Nebula
3. Rez outer Asteroid Belt
4. Use PW to remove all counters from Femme and install it, target Asteroid Belt for bypass (gets the F label)
5. Continue past Asteroid Belt
6. Rez Nebula
7. Femme can match strength of Nebula and break subs

**Comment by JoelCFC25** [comment] 2016-11-07 11:19
Closing due to lack of reproduction or follow-up. Feel free to reopen if it happens again...

**Closed by JoelCFC25** 2016-11-07 11:19 UTC
Labels: can't reproduce
