### ISSUE TITLE
London Library clones chameleon at end of turn.

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#409] opened 2015-07-21 14:44 UTC
If i install a chameleon on london library and leave it there untill end of turn it clones the card and puts one in my hand and one in my heap.

**Comment by JoelCFC25** [comment] 2015-07-21 14:47
Duplicate of #325. Use the workaround suggested there in the meantime.

**Comment by gtgettel** [comment] 2015-07-22 02:33
Might work to split the end of turn into a end of turn phase and clean up phase. chameleon could occur in end of turn and london library happens in clean up. thoughts?

**Closed** 2016-01-07 17:06 UTC
Labels: bug, duplicate
