### ISSUE TITLE
Stargate trashed by Balista mid-run

### ISSUE THREAD

**Issue by StarpunkPrime** [mtgred/netrunner#6049] opened 2021-09-16 21:30 UTC
Link to bug replay: https://jinteki.net/bug-report/6a2d86ea-c963-4df0-b3be-1bba4192b765?b=0

Description:

I used Stargate to run R&D, which was protected by Ballista. Corp trashed Stargate then I breached, but I accessed cards like normal instead of draw 3/trash 1. Somebody in Discord said this wasn't working correctly.
This was a demo game where I was controlling both sides.

**Comment by cardboardtech** [comment] 2021-09-16 21:58
Thanks for the report!

duplicate of https://github.com/mtgred/netrunner/issues/5754

**Closed** 2021-09-27 14:17 UTC
