### ISSUE TITLE
Issue: Selecting Cards Freeze (Personal Workshop)

### ISSUE THREAD

**Issue by AlecGamble** [mtgred/netrunner#1604] opened 2016-06-09 14:13 UTC
Hi guys.

Since the update yesterday(?) I've been having issues with effects which force me to select a card by clicking on that card. Although I don't know if this applies to all instances it applied in two cases in my game earlier the most notable being Personal Workshop. At the start of my turn whilst a card is installed on personal workshop I get the prompt to select a card to remove a counter from. Selecting the card on personal workshop highlights the card but doesn't fire the effect as it used to. Furthermore clicking on the done button once it's finished (as i expect the change was to give the player greater control over selecting the card and choosing when they want to submit the effect) has no effect and then the only action left is to use /remove-prompt to remove the prompt but without the /counter n command working there's no way to remove counters from items on personal workshop.

I found the same issue when I was also trying to access a server with multiple unrezzed upgrades although after playing again I'm not sure if this was an issue, something more specific or if I just missed something because I think I've tried again and it seemed fine?

**Comment by nealterrell** [comment] 2016-06-09 15:33
I can't reproduce the multiple-upgrades thing, so please let me know if you experience it again. The PW thing is known and a fix has been submitted in #1601. For now, I have had success with clicking "Done" when asked to select a card at start of turn, then using the "Remove X counters" ability on the card itself. That ability is working fine, but you will need to adjust your credits up by 1.

**Comment by FarCryFromHuman** [comment] 2016-06-09 19:14
I just had the same problem when asked to choose a target for Femme. I got the targeting reticle, but couldn't click any ice (rezzed or not). The Done button didn't do anything and I had to use /close-prompt to return to the normal game loop.

**Comment by nealterrell** [comment] 2016-06-09 19:43
Was Femme installed from hand?

**Comment by FarCryFromHuman** [comment] 2016-06-09 19:43
Yes, during a run after I manually pulled it off of the broken Personal Workshop.

**Comment by nealterrell** [comment] 2016-06-09 19:44
Ok, it's definitely the PW then. Thanks.

**Closed** 2016-06-10 03:06 UTC
Labels: bug, cards
