### ISSUE TITLE
runner status box pushes under grip/hand box at some zooms

### ISSUE THREAD

**Issue by mbs** [mtgred/netrunner#3045] opened 2018-02-02 03:45 UTC
The runner's status box pushes under the grip/hand box, almost invisibly, at some zooms.  Runner cannot scroll to see or manipulate the hidden status elements.

![image](https://user-images.githubusercontent.com/50592/35715561-e06e73d6-0798-11e8-8477-0c44ad9ffb4b.png)

(see lower-left of screenshot; e.g. brain damage stat cannot be seen nor adjusted)

**Comment by danhut** [comment] 2018-02-17 04:17
The question is what should happen in this case.  The UI is designed for a decent sized screen, or you can just zoom out.   I think supporting a different behaviour would require a lot of work and mean we'd be building a fully reactive UI which I don't see happening.

However a specific fix for this one box might be do-able.

**Comment by mbs** [comment] 2018-02-18 03:57
There seems to be plenty of room for it elsewhere; what about possibly putting the runner's score area and stats box next to the corp's score/stats boxes?

**Comment by msbeck** [comment] 2018-03-17 14:02
The issue is a problem for myself as well. I often feel the need to zoom in quite a bit, and even with a large widescreen monitor the player stats mess up before it's large enough for me. 

As you can see in the screenshot, the zoom level doesn't even make the cards that large before the stats start getting lost.

The stats at the bottom aren't really needed as much, so I usually let them fall off, but yes it could use some improvement.

I think this points towards a slightly bigger task of perhaps sprucing up the UI in general. Fully reactive UI is unlikely to get any dev time given that cards are coming in so frequently and a box is arriving shortly. But rearranging things or having an alternate way of presenting the information might be feasible.

**Comment by jwarwick** [comment] 2018-03-17 16:20
One easy fix I thought of was shifting the scored agenda boxes to the right and shifting the info boxes into that empty space. We already put currents and rfg cards in that column.

**Comment by msbeck** [comment] 2018-03-17 17:59
That could work, seemingly without much hassle. I can make a concept for that to see visually what it would look like.

In the meantime, I could also try to come up with some options for slimming it down a little.

Many times you'll see information like where we're talking about as icons and their associated numbers. I was imagining that there must be some solution that could turn that info into a bar somewhere. I'd like to investigate what that might look like and where a good placement for it would be.

**Closed** 2024-03-21 01:28 UTC
Labels: game interface
