### ISSUE TITLE
Earth Station's Art Broken Again

### ISSUE THREAD

**Issue by Trottster** [mtgred/netrunner#7780] opened 2024-09-28 18:41 UTC
Broken image link in every instance if Earth Station's art. This was an issue that was apparently resolved a week or so ago, but has returned. At that time, I believe other cards were affected as well--cannot remember which though.

**Comment by NBKelly** [comment] 2024-10-05 07:10
Yeah, last time it was caused by the images not being there when we updated to the remastered arts for ashes (the flips aren't available via nrdb, so we have to do it manually), this time it was caused by some of the foreign-language cards overwriting the correct paths for the flips. It should be fixed in our next patch (hopefully in a day or so).

**Closed** 2024-10-10 20:05 UTC
