### ISSUE TITLE
"Runner accesses OK" issue is back

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1662] opened 2016-06-19 17:38 UTC
I noticed this while spectating:

![Chat Log](http://imgur.com/lgBXoYQ.png)

It happened with this board state:

![Board State](http://imgur.com/fBOIftD.png)

Both images at imgur album here: [http://imgur.com/a/BrNSv](http://imgur.com/a/BrNSv)

**Comment by JoelCFC25** [comment] 2016-06-20 14:37
I'm looking at how this issue was fixed previously. It would help to know which server was being run (HQ or R&D).

**Comment by FarCryFromHuman** [comment] 2016-06-20 14:43
This was during a run on R&D. Sorry, I should have pointed that out. 

It might be nice to have the message for TTW name which server the runner is gaining multi-access on. There's the corner case of the runner clicking on it while not in-run (or on a non-R&D/HQ run) and getting something weird, but the rules text on the card implies that the paid ability can only be used during a run on R&D/HQ. Can abilities on cards be disabled based on game state?

**Comment by JoelCFC25** [comment] 2016-06-20 14:48
The ability already requires a run to be present in order to use it:  line 1077:  `:req (req (:run @state))`

It can't be refined further than that or it will be rendered unusable during Sneakdoor runs or other bizarre (but valid) cases like using Copycat.

**Comment by FarCryFromHuman** [comment] 2016-06-20 14:50
Ah, that makes sense. I imagine this isn't worth the technical effort to fix; it works correctly as implemented and if you can't read you probably shouldn't play this game >.>

**Comment by JoelCFC25** [comment] 2016-07-13 16:12
Any more signs of this? I have a strong suspicion that it was fixed in one of Neal's voluminous PRs.

**Comment by FarCryFromHuman** [comment] 2016-07-13 16:13
I haven't seen it since but I also haven't had the chance to play/spectate much lately. I might be able to attempt recreation this weekend but no promises.

**Comment by JoelCFC25** [comment] 2016-07-19 04:05
Confirmation in #1794 that this is still happening in some instances. Grrrr....

**Comment by kyokorebit** [comment] 2016-08-06 09:20
Hi I'm kyokorebit from that game. I used TTW a lot and the "accesses OK" happened quite a few times. I noticed that it tends to happen whenever I'm clicking too fast inbetween the access prompts. Hope it helps.

**Comment by JoelCFC25** [comment] 2016-10-12 14:12
We strongly suspect that this is caused by fast clicking, so let's redirect all progress on this to the original issue at #468.

**Closed by JoelCFC25** 2016-10-12 14:12 UTC
Labels: bug
