### ISSUE TITLE
Adam Derectives

### ISSUE THREAD

**Issue by PinkWarrior** [mtgred/netrunner#649] opened 2015-08-31 10:56 UTC
Adam installs all directives in your deck not just 1 of each so if you run multiples you have to shuffle them back into the deck and shows your opponent which ones you value more.

**Comment by queueseven** [comment] 2015-08-31 11:28
Thanks for reporting. Duplicate of #628 

Didn't have the time to fix it yet. Maybe someone else wants to try? We just need to add a `group-by` and a `map fst`.

**Closed** 2015-08-31 22:58 UTC
Labels: bug, duplicate
