### ISSUE TITLE
Khusyuk writes numbers accessed instead of credits chosen in console, and "top" number missing

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4123] opened 2019-03-19 23:03 UTC
When runner selected 1 credit install cost on Khusyuk, things worked as it should, but the text in console was wrong: it said <runner> chooses an install cost of 6 [c] and reveals (top:) <card1>,<card2>...

![image](https://user-images.githubusercontent.com/1651150/54647522-1b521680-4aa3-11e9-82b8-c7a4d41eb5de.png)

It should be

<runner> chooses an install cost of **1** [c] and reveals (top:**6**) <card1>,<card2>...

**Comment by NoahTheDuke** [comment] 2019-03-19 23:14
Duplicate of #4104, but thank you for the detailed report!

**Closed** 2019-03-20 15:22 UTC
Labels: bug, cards, duplicate
