### ISSUE TITLE
Pumping Switchblade failed.

### ISSUE THREAD

**Issue by bigfleet** [mtgred/netrunner#2263] opened 2016-12-22 23:22 UTC
Please describe the circumstances of your error here.

I'm Nasir, and I've SMC'ed a cloak into play, with a Switchblade on the table.  This was trying to pump it to break a Komainu (or a Tsurugi maybe)

Stack Trace:
```clojure
Error do ability Switchblade #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Numbers ops "Numbers.java" 1013]}]
 :trace
 [[clojure.lang.Numbers ops "Numbers.java" 1013]
  [clojure.lang.Numbers gt "Numbers.java" 229]
  [clojure.lang.Numbers gt "Numbers.java" 3864]
  [game.core$play_ability$fn__5748 invoke "actions.clj" 186]
  [game.core$should_trigger_QMARK_ invokeStatic "abilities.clj" 20]
  [game.core$should_trigger_QMARK_ invoke "abilities.clj" 10]
  [game.core$should_trigger_QMARK_ invokeStatic "abilities.clj" 15]
  [game.core$should_trigger_QMARK_ invoke "abilities.clj" 10]
  [game.core$can_trigger_QMARK_ invokeStatic "abilities.clj" 31]
  [game.core$can_trigger_QMARK_ invoke "abilities.clj" 26]
  [game.core$resolve_ability_eid invokeStatic "abilities.clj" 131]
  [game.core$resolve_ability_eid invoke "abilities.clj" 113]
  [game.core$resolve_ability invokeStatic "abilities.clj" 111]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$resolve_ability invokeStatic "abilities.clj" 109]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$do_play_ability invokeStatic "actions.clj" 176]
  [game.core$do_play_ability invoke "actions.clj" 170]
  [game.core$play_ability invokeStatic "actions.clj" 193]
  [game.core$play_ability invoke "actions.clj" 178]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 145]
  [game.main$handle_command invoke "main.clj" 134]
  [game.main$run$fn__26832 invoke "main.clj" 180]
  [game.main$run invokeStatic "main.clj" 170]
  [game.main$run invoke "main.clj" 164]
  [game.main$_main$fn__26867 invoke "main.clj" 234]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by nealterrell** [comment] 2016-12-23 01:06
Duplicate of #2260 etc. We'll have a fix soon. Thanks for the report!

**Closed by nealterrell** 2016-12-23 01:06 UTC
