### ISSUE TITLE
Using Flower Sermon during Run locked up game

### ISSUE THREAD

**Issue by TitaniumTaz** [mtgred/netrunner#5098] opened 2020-05-10 23:13 UTC
Runner was in between outer ICE and inner ICE on R&D. Corp played Flower Sermon.
Corp drew 2, selected card from HQ to go on R&D.
Runner could not do anything because system indicated they were waiting on Flower Sermon
Corp could not do anything because system indicated they were waiting on Runner to select what to do at (inner) ICE.

Then the game got confused when we tried undo-click and various rejoins. We could rejoin, but not interact with any cards.

**Comment by NoahTheDuke** [comment] 2020-05-10 23:51
Thanks for the report!

**Comment by lostgeek** [comment] 2020-05-12 14:58
I couldn't reproduce this. Can you take a screenshot if this should happen again?

**Comment by francescopellegrini** [comment] 2023-12-03 13:20
@NoahTheDuke can be closed as obsolete.

**Closed** 2023-12-03 13:20 UTC
Labels: bug, card
