### ISSUE TITLE
Card options from Stack are blank (Street peddler, Djinn, etc)

### ISSUE THREAD

**Issue by goeshi** [mtgred/netrunner#2302] opened 2017-01-09 11:29 UTC
Found a bug where the pop-up list for card options from the stack appear all blank. For example when using Djinn's ability to find a virus. Thx

**Comment by mtgred** [comment] 2017-01-09 13:41
The problem is fixed now. Just refresh your browser to solve the issue.

**Closed** 2017-01-12 15:41 UTC
