### ISSUE TITLE
Suggestion: prevent installation of programs if insufficient MU

### ISSUE THREAD

**Issue by koalabearski** [mtgred/netrunner#1342] opened 2016-03-13 16:58 UTC
Related issue: #600 - where going into negative MU is introduced

MU's can go negative for good reason and I like the flexibility it gives you in sorting things out.  However, you can currently install a program while going in to negative MU and you are expected to trash programs to balance it out again.

Some suggestions:
* when you are trying to install without enough MU, prompt to trash programs first (or cancel)
* prevent installation until you have enough MU
* allow undo install - though I can see that being complicated

**Comment by zaroth** [comment] 2016-03-14 12:03
Duplicate of #1257

**Closed by zaroth** 2016-03-14 12:03 UTC

**Comment by koalabearski** [comment] 2016-03-14 13:59
Sorry, did a little research before posting but not enough :).  Thanks!
