### ISSUE TITLE
Daily Quest hosted on Full Immersion RecStudio issue

### ISSUE THREAD

**Issue by p4ulyg** [mtgred/netrunner#5135] opened 2020-05-25 16:02 UTC
If a Daily Quest is hosted on Full Immersion RecStudio then currently the runner does not gain the 2 credits that they should when they make a successful run on the server.

**Comment by NoahTheDuke** [comment] 2020-05-25 21:55
Thanks for the report!

**Comment by NoahTheDuke** [comment] 2020-05-26 01:10
Duplicate of #4571.

**Closed by NoahTheDuke** 2020-05-26 01:10 UTC
Labels: bug, card
