### ISSUE TITLE
Scoring a Megaprix with a counter as your 7th point doesn't "win" the game

### ISSUE THREAD

**Issue by anarchomushroom** [mtgred/netrunner#6017] opened 2021-08-11 16:12 UTC
Link to bug replay: https://jinteki.net/bug-report/472b7a8a-4259-472f-90ff-d71d4202757b?b=0

Description: When you score a Megaprix Qualifier with a counter on it, it doesn't count as winning the game even though the game recognises you have 7 points in your score area. The splash screen doesn't appear and it doesn't count as a won game (I think) on your stats.

[EDITME] Have a Megaprix Qualifier in either score area. Get to 5 points (doesn't work with 6, as the normal point twigs the win condition). Score a Megaprix Qualifier to gain 6, then 7 points. Game does not "win".

**Comment by francescopellegrini** [comment] 2021-08-12 12:24
Duplicate of #5968

**Comment by BlueHairedHackerCatgirl** [comment] 2021-08-30 19:01
FWIW the game does win usually at the next click complete or turn swap.

**Closed** 2021-09-14 19:38 UTC
