### ISSUE TITLE
Mr. Li offering the same card 2 clicks in a row when card not chosen

### ISSUE THREAD

**Issue by michaelryanmcguire** [mtgred/netrunner#1638] opened 2016-06-13 15:07 UTC
Mr. Li doesn't seem to be reliably dumping cards to the bottom of the stack.  I had a single "Lawyer Up" in my deck.  I clicked Mr. Li for click 1, had a choice between Lawyer Up and another card, chose the other card, clicked Mr. Li for click 2, and saw Lawyer Up again.  

Happened in chrome on windows, if it matters.  

edit: tried to reproduce at length with mr. li and window, doesn't seem to be reproducible :(

**Comment by nealterrell** [comment] 2016-06-13 15:55
Any other notable cards in play that may have been affecting your ability to draw, or other interactions with your stack?

**Comment by michaelryanmcguire** [comment] 2016-06-13 17:14
Nothing I can see.  Here's the [decklist](https://netrunnerdb.com/en/decklist/35677/gimme-three-steps) in case you see something I don't.

**Comment by JoelCFC25** [comment] 2016-09-03 17:05
Closing this since it there have been no subsequent reports and no reproduction steps. If it comes up again, open a new issue. Thanks!

**Closed by JoelCFC25** 2016-09-03 17:05 UTC
Labels: can't reproduce
