### ISSUE TITLE
Heap breaker lose the Cybertrooper boost if placed on Flame-out

### ISSUE THREAD

**Issue by Diogened** [mtgred/netrunner#5354] opened 2020-11-06 13:59 UTC
Hi.

Here is the situation :
Flame-out and Cybertrooper Talut are installed. Every heap breakers are in the heap (Paperclip, MKUltra, Black Orchestra). 

If I make a run, encounter an ice, I can install an heap breaker. It will come on the board with +2 strength from Cybertrooper.

But when I host the heap breaker on Flame-out, it loses its boost (meaning it goes back to the original strength of the breaker).

Can this be fixed, so that the Cybertrooper boost can be kept?

Thanks.
Diogene

**Comment by NoahTheDuke** [comment] 2020-11-08 00:54
Thanks for the report! Duplicate of #4770

**Closed by NoahTheDuke** 2020-11-08 00:54 UTC
