### ISSUE TITLE
MongoError on user creation

### ISSUE THREAD

**Issue by GordonsBeard** [mtgred/netrunner#138] opened 2015-03-18 06:01 UTC
I've cloned this and have it running on my own server currently (way rad), but I notice whenever someone creates a new user this error appears:

```
MongoError: Message contains no documents
    at Object.toError (/netrunner/node_modules/mongodb/lib/mongodb/utils.js:114:1  1)
    at /netrunner/node_modules/mongodb/lib/mongodb/collection/core.js:636:22
    at Server.Base._callHandler (/netrunner/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /netrunner/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at MongoReply.parseBody (/netrunner/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/netrunner/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (/netrunner/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/netrunner/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
```
It doesn't seem to affect anything, users are still created and things can progress normally, but I wondered if this was a known issue.

**Comment by Saintis** [comment] 2015-12-30 23:00
Is this still happening? I cannot reproduce.

**Comment by queueseven** [comment] 2016-04-19 07:36
I also cannot reproduce this. I'm going to close this issue since it's already open for over one year with no progress and no answer. If this is still happening, feel free to reopen and add more information.

**Closed by queueseven** 2016-04-19 07:36 UTC
Labels: dev, question
