### ISSUE TITLE
On The Lam does not prevent damage

### ISSUE THREAD

**Issue by dagguh** [mtgred/netrunner#3966] opened 2018-12-09 20:30 UTC
### Steps
1. Install Tech Trader
2. Play On The Lam, targeting the Tech Trader
3. Run into a 3-advancement Junebug
4. See the damage prevention prompt
5. Click On The Lam with the intention to prevent 3 net damage

### Expectation
On The Lam is trashed. 3 net damage is prevented. Eventually, there's a card-local popup to trigger the self-trash ability.

### Reality
Nothing happens. There's no way to prevent the damage.

### Workaround
Eat the net damage, accidentally revealing your Grip, manually drag the cards from the Heap.
If you're going to be unfairly flatlined and you want to avoid a loss, draw up first and then try to sort out the mess.

**Comment by tolaasin** [comment] 2018-12-10 13:53
Duplicate of #3746

**Closed** 2019-01-11 03:49 UTC
Labels: bug, cards
