### ISSUE TITLE
Meridian makes the runner stuck

### ISSUE THREAD

**Issue by percomis** [mtgred/netrunner#6851] opened 2022-12-19 22:22 UTC
When as a runner you take Meridian to your score area it seems you get stuck in approaching Meridian.

**Comment by francescopellegrini** [comment] 2022-12-20 18:01
This was allegedly fixed by #6843, which was included in the latest release of 3 hours ago: could you try again and see if the problem is still there?

**Comment by francescopellegrini** [comment] 2023-01-02 15:33
Might as well close this.

**Closed** 2023-01-02 16:13 UTC
