### ISSUE TITLE
Runner with 3 clicks couldn't initiate run vs. Ruhr Valley + Enhanced Login Protocols

### ISSUE THREAD

**Issue by jamesgaines** [mtgred/netrunner#2610] opened 2017-06-22 00:46 UTC
Runner: Nasir, Corp: AgInfusion

Current: Enhanced Login Protocol

Server 1: 
- Nisei Mk II w/ 1 advancement counter
- Ruhr Valley (rezzed)
- Caprice Nisei (unrezzed)
- 2 ice: Chimaera (innermost, unrezzed); Excalibur (outermost, unrezzed)

Runner used their first click to take money from Zona Sul Shipping, then found that they were unable to run on Server 1. They tried giving themselves extra clicks, but it didn't work. We had them run into a Mindgame on R&D and purposefully win the psi game. Once the run was redirected, they were able to continue the run. 

As far as I could guess, maybe Ruhr was accidentally setting the click requirement arbitrarily high?

![screenshot 1](https://user-images.githubusercontent.com/10165610/27412420-49694006-56a9-11e7-8135-59f6e9de3d0a.jpg)

**Comment by JoelCFC25** [comment] 2017-06-22 00:52
Duplicate of #2109.

**Comment by jamesgaines** [comment] 2017-06-22 00:55
Oh, sorry. Thanks for the redirect!

**Closed** 2017-06-22 00:56 UTC
Labels: bug, cards, duplicate
