### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by MulganDragon** [mtgred/netrunner#6987] opened 2023-08-03 18:43 UTC
Link to bug replay: https://jinteki.net/bug-report/b3c099ed-225a-4faa-9efc-f879d3d75798?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.
when running hq using Beatriz and encountering Jaguarundi it breaks the game. the first time it broke there was a hush and a kyuban on the ice but removing those did not fix the issue. the only way to fix it was to make a run without beatriz.

**Comment by NBKelly** [comment] 2023-08-04 00:38
Duplicate of #6968 - already fixed, will be deployed soon

**Comment by NBKelly** [comment] 2023-08-05 00:07
@NoahTheDuke this can be closed

**Closed** 2023-08-05 03:10 UTC
