### ISSUE TITLE
Two 'the future perfect' in archives

### ISSUE THREAD

**Issue by ryanedward24** [mtgred/netrunner#101] opened 2015-02-12 22:41 UTC
just ran into a bug wherein two future perfects in archives results in a never ending loop of psi games.
sequence of events seemed to be 
-runner accesses archives
-i, playing nisei division, get two credits
-psi game triggers
-we play psi game
-he lost
-i get two more credits for some reason
-we play another psi game
-he loses
-i get two more credits from my ID ability
-repeat all previous steps in an endless loop that does not allow runner to jack out

to break the loop we decided we would both bid zero and move them back to my archives from his scored area but this just resulted in
-he scored TFP
-i got two more credits
-new psi game for second nisei
-he scored the second TFP
-i got two more credits
-new psi game for non-existant TFP
-he scored another TFP
-i got two more credits
-new psi game for non-existant TFP
-another infinite loop but this time he had like 15 TFP in his scored area.

**Comment by mtgred** [comment] 2015-03-08 02:59
Thanks for reporting the issue. There was a issue preventing the run from ending if the Corp has an active prompt (Future Perfect Psi game in this case). The issue is now fixed and will be deployed with the next server update.

**Closed** 2015-03-08 04:07 UTC
