### ISSUE TITLE
Tri-Maf Contact interaction with Apocalypse 

### ISSUE THREAD

**Issue by Tr33beard** [mtgred/netrunner#940] opened 2015-12-01 18:14 UTC
If the runner has a Tri-maf Contact installed and then Apocalypses, they take meat damage as if Tri-maf had been trashed. However, the card is only being turned face-down, not being trashed. The meat damage shouldn't trigger in this occurrence. Obviously this isn't a high priority fix as Tri-maf isn't a super common card, but it accidentally flatlined my opponent earlier today.

**Comment by JoelCFC25** [comment] 2015-12-01 20:15
Thanks for the report--duplicate of #901.

**Closed** 2015-12-03 05:17 UTC
Labels: duplicate
