### ISSUE TITLE
Hivemind and tokens

### ISSUE THREAD

**Issue by CZCuckoo** [mtgred/netrunner#738] opened 2015-09-20 14:06 UTC
Over the last week, removing tokens from viral breeding ground will remove the token, and the click, tell everyone that you have added the token to hivemind, and then reset to the original 1 as soon as you click "done."

**Comment by nealterrell** [comment] 2015-09-22 01:05
I can't reproduce this :(. Was either card hosted on something else? I installed VBG and Hivemind. Next turn, I click VBG to transfer a second token to Hivemind, with VBG ending with 0 tokens.

**Comment by CZCuckoo** [comment] 2015-09-22 01:07
It was hosted on progenitor. I haven't tested this with hivemind unhosted.

**Comment by nealterrell** [comment] 2015-09-23 01:29
Let me know if you see the issue again. I am getting expected behavior on my dev machine even when hosting Hivemind on Progenitor. The server hasn't been updated with new code for ~2 weeks; it's possible the issue has already been fixed, awaiting deployment to live.

**Comment by JoelCFC25** [comment] 2015-10-21 14:31
@CZCuckoo have you been able to reproduce this problem? If not, I will close the issue.

**Comment by CZCuckoo** [comment] 2015-10-21 14:33
I haven't really tested it since you mentioned new code in ~2 weeks. I'll
do so as soon as I can. Worst come to worst, you can close the issue, and
I'll resubmit if I find that it's happening again in the same
circumstances. Thanks.

**Closed** 2015-11-12 15:37 UTC
Labels: can't reproduce
