### ISSUE TITLE
Still problems with Blackguard

### ISSUE THREAD

**Issue by brokenimage321** [mtgred/netrunner#2122] opened 2016-10-24 21:54 UTC
Twice, while exposing cards with Blackguard installed, the game threw an error. This was the first time.
IIRC, this happened while playing Sattelite Uplink with Blackguard installed. 

Stack Trace:
```clojure
Error do select  #error {
 :cause "Wrong number of args (2) passed to: core/rez"
 :via
 [{:type clojure.lang.ArityException
   :message "Wrong number of args (2) passed to: core/rez"
   :at [clojure.lang.AFn throwArity "AFn.java" 429]}]
 :trace
 [[clojure.lang.AFn throwArity "AFn.java" 429]
  [clojure.lang.AFn invoke "AFn.java" 36]
  [game.core$fn__12685 invokeStatic "hardware.clj" 65]
  [game.core$fn__12685 invoke "hardware.clj" 50]
  [game.core$do_effect invokeStatic "abilities.clj" 257]
  [game.core$do_effect invoke "abilities.clj" 253]
  [game.core$do_ability invokeStatic "abilities.clj" 238]
  [game.core$do_ability invoke "abilities.clj" 211]
  [game.core$resolve_ability_eid invokeStatic "abilities.clj" 136]
  [game.core$resolve_ability_eid invoke "abilities.clj" 113]
  [game.core$resolve_ability invokeStatic "abilities.clj" 111]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$trigger_event_sync_next invokeStatic "events.clj" 48]
  [game.core$trigger_event_sync_next doInvoke "events.clj" 40]
  [clojure.lang.RestFn applyTo "RestFn.java" 157]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 587]
  [game.core$trigger_event_sync invokeStatic "events.clj" 64]
  [game.core$trigger_event_sync doInvoke "events.clj" 55]
  [clojure.lang.RestFn invoke "RestFn.java" 497]
  [game.core$resolve_expose invokeStatic "rules.clj" 467]
  [game.core$resolve_expose invoke "rules.clj" 461]
  [game.core$expose$fn__4312 invoke "rules.clj" 490]
  [game.core$effect_completed invokeStatic "events.clj" 240]
  [game.core$effect_completed invoke "events.clj" 236]
  [game.core$trigger_event_sync$fn__3847 invoke "events.clj" 65]
  [game.core$effect_completed invokeStatic "events.clj" 240]
  [game.core$effect_completed invoke "events.clj" 236]
  [game.core$trigger_event_sync_next invokeStatic "events.clj" 53]
  [game.core$trigger_event_sync_next doInvoke "events.clj" 40]
  [clojure.lang.RestFn applyTo "RestFn.java" 157]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 587]
  [game.core$trigger_event_sync invokeStatic "events.clj" 64]
  [game.core$trigger_event_sync doInvoke "events.clj" 55]
  [clojure.lang.RestFn invoke "RestFn.java" 497]
  [game.core$expose invokeStatic "rules.clj" 475]
  [game.core$expose invoke "rules.clj" 469]
  [game.core$expose invokeStatic "rules.clj" 472]
  [game.core$expose invoke "rules.clj" 469]
  [game.core$fn__11031 invokeStatic "events.clj" 911]
  [game.core$fn__11031 invoke "events.clj" 910]
  [game.core$do_effect invokeStatic "abilities.clj" 257]
  [game.core$do_effect invoke "abilities.clj" 253]
  [game.core$do_ability invokeStatic "abilities.clj" 238]
  [game.core$do_ability invoke "abilities.clj" 211]
  [game.core$resolve_ability_eid invokeStatic "abilities.clj" 136]
  [game.core$resolve_ability_eid invoke "abilities.clj" 113]
  [game.core$resolve_ability invokeStatic "abilities.clj" 111]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$resolve_ability invokeStatic "abilities.clj" 109]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$resolve_select invokeStatic "abilities.clj" 376]
  [game.core$resolve_select invoke "abilities.clj" 364]
  [game.core$select invokeStatic "actions.clj" 166]
  [game.core$select invoke "actions.clj" 151]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 150]
  [game.main$handle_command invoke "main.clj" 139]
  [game.main$run$fn__25311 invoke "main.clj" 185]
  [game.main$run invokeStatic "main.clj" 175]
  [game.main$run invoke "main.clj" 169]
  [game.main$_main$fn__25346 invoke "main.clj" 239]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by erbridge** [comment] 2016-10-24 22:22
Duplicate of #2119.

**Closed** 2016-10-26 03:58 UTC
Labels: bug, cards, duplicate, easy
