### ISSUE TITLE
Can't fully view all cards in hand when browser is zoomed-in and have exactly six cards.

### ISSUE THREAD

**Issue by Azgaroux** [mtgred/netrunner#949] opened 2015-12-04 11:19 UTC
Can't fully view all cards in hand when browser is zoomed-in to 50/60% and have exactly six(6) cards.

**Comment by GordonsBeard** [comment] 2015-12-04 15:23
Which browser? What is your resolution?

**Comment by Azgaroux** [comment] 2015-12-05 03:04
Browsers: Chrome ver. 47.0.2526.73, Chromium ver. 46.0.2480.0 and Foxfire ver. 42.0. Resolution 1366x768.

**Comment by nealterrell** [comment] 2015-12-05 17:06
Do you mean maximized instead of minimized? Which part of the cards gets cut off? Have you tried F11 (full screen) and/or zooming out?

**Comment by Azgaroux** [comment] 2015-12-07 01:29
It's either minimized,maximized or in full screen and as long as you have 6 cards in hand and a zoomed-in browser below 50%. Sorry the title is confusing, I'll just edit it for clarification.

**Comment by zaroth** [comment] 2016-03-14 12:54
#1335 is a possible fix for this.

**Comment by JoelCFC25** [comment] 2016-09-08 01:17
Confirmed that this is still an issue--a bizarre one--at least in Chrome 53.0.2785.101 (64-bit) on MacOS.

**Comment by Saintis** [comment] 2018-08-10 20:51
Cannot reproduce on Chrome. On Firefox and Safari, the 6th card sometimes moves to a second row on very zoomed out settings (but doesn't disappear). And now with the ability to expand the hand to a bigger window this will not be an issue.

**Closed by Saintis** 2018-08-10 20:51 UTC
Labels: bug, game interface
