### ISSUE TITLE
Ultraviolet Clearance allows installation of assets/agendas on centrals

### ISSUE THREAD

**Issue by hiddenaway1** [mtgred/netrunner#3811] opened 2018-07-25 17:35 UTC
Not sure if this is because of how I'm testing Jinja City Grid and just playing solo but UVC is allowing me to install cards illegally!

![image](https://user-images.githubusercontent.com/35308609/43217402-704d8004-9039-11e8-80c0-bf42267bd305.png)

**Comment by NoahTheDuke** [comment] 2018-07-25 18:09
Thanks for the report!

**Comment by jwarwick** [comment] 2018-10-17 18:04
Duplicate of #3894

**Closed by jwarwick** 2018-10-17 18:04 UTC
Labels: bug, duplicate
