### ISSUE TITLE
TODO: Scavenge

### ISSUE THREAD

**Issue by shazzner** [mtgred/netrunner#72] opened 2015-01-20 08:34 UTC
Would be very nice for it to work! Test running a femme fatal, then trying to scavenge it doesn't work. Then attempting to bring it back out manually seems to break it.

**Comment by anathomical** [comment] 2015-01-30 23:40
The breaking bit is actually a problem with Test Run, I suspect, not with anything else.  For instance, if you Test Run a Femme and then run a server but hit (say) a Will o' Wisp, Test Run's "put on top of the Stack" clause will still trigger.

**Comment by mtgred** [comment] 2015-02-06 10:24
Test run has been improved to handle the case where the fetched cards is reinstalled before the end of turn.

**Comment by anathomical** [comment] 2015-02-06 16:58
Confirmed that removing a Test Run-installed card from play (either moving it to the Heap or to the Grip) will mean that that card is no longer put back on top of the Stack at the end of the turn by Test Run.

Minor issue: the chat console still reports that the card IS put back on top of the Heap.  It isn't, so things work as intended, but the extra communication may confuse some users.

**Comment by JoelCFC25** [comment] 2015-06-19 13:37
This one can be closed based on #192.

**Closed** 2015-06-19 16:22 UTC
