### ISSUE TITLE
Obelus drawing cards at the wrong time

### ISSUE THREAD

**Issue by atomicxistence** [mtgred/netrunner#2686] opened 2017-08-03 18:21 UTC
When running with Counter Surveillance, Obelus draws cards from your deck BEFORE you access the cards and the run ends

**Comment by JoelCFC25** [comment] 2017-08-03 19:30
Duplicate of #2675.

**Closed by JoelCFC25** 2017-08-03 19:30 UTC

**Comment by atomicxistence** [comment] 2017-08-03 20:54
sorry for the duplication. thanks for the support!
