### ISSUE TITLE
Game becomes unresponsive after trying to play Exclusive Party

### ISSUE THREAD

**Issue by thomasbalmer** [mtgred/netrunner#4142] opened 2019-03-22 13:58 UTC
When trying to play exclusive party game becomes unresponsive. Card is eventually moved to the temporary zone. I cannot then click on any elements in the game window and get a response.

Can leave and rejoin game and that seems to solve the issue until the next copy of the card comes out again.

**Comment by NoahTheDuke** [comment] 2019-03-22 14:13
Duplicate of #4089. Gonna leave this one up so others can see.

**Closed** 2019-03-28 14:50 UTC
Labels: bug, duplicate
