### ISSUE TITLE
Cannot resolve spin doctor and daily business show at same time

### ISSUE THREAD

**Issue by newmanr4** [mtgred/netrunner#7175] opened 2023-10-08 05:25 UTC
Link to bug replay: https://jinteki.net/bug-report/ec0c58e8-f52c-41a0-af34-b21c0a02f67a?b=0

**Comment by NBKelly** [comment] 2024-07-05 05:03
DBS (and all drawing) was changed to operate on the set-aside zone during triggers, rather than the hand. Those are in the top left corner of the screen.

Closed as duplicate of #7258

**Closed by NBKelly** 2024-07-05 05:03 UTC
