### ISSUE TITLE
Untrashable Jeeves (Perhaps a slums issue, error log included)

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#2431] opened 2017-03-16 02:19 UTC
The runner attempted to remove Jeeves using Slums. For the rest of the game, Jeeves could not be trashed in any way (by using /rfg, overwriting, manually dragging, or trashed by the runner). After the runner attempted to Slums Jeeves, Jeeves did not trigger automatically but could be used manually to gain a click. Also Jeeves could not be derezzed.

Stack Trace:
```clojure
Error do move Jeeves Model Bioroids #error {
 :cause "Wrong number of args (5) passed to: PersistentArrayMap"
 :via
 [{:type clojure.lang.ArityException
   :message "Wrong number of args (5) passed to: PersistentArrayMap"
   :at [clojure.lang.AFn throwArity "AFn.java" 429]}]
 :trace
 [[clojure.lang.AFn throwArity "AFn.java" 429]
  [clojure.lang.AFn invoke "AFn.java" 48]
  [game.core$trigger_leave_effect invokeStatic "installing.clj" 28]
  [game.core$trigger_leave_effect invoke "installing.clj" 18]
  [game.core$deactivate invokeStatic "installing.clj" 45]
  [game.core$deactivate invoke "installing.clj" 39]
  [game.core$deactivate invokeStatic "installing.clj" 42]
  [game.core$deactivate invoke "installing.clj" 39]
  [game.core$move invokeStatic "cards.clj" 94]
  [game.core$move invoke "cards.clj" 58]
  [game.core$resolve_trash_end invokeStatic "rules.clj" 301]
  [game.core$resolve_trash_end doInvoke "rules.clj" 297]
  [clojure.lang.RestFn invoke "RestFn.java" 500]
  [clojure.lang.AFn applyToHelper "AFn.java" 171]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 587]
  [game.core$resolve_trash$fn__5507 invoke "rules.clj" 316]
  [game.core$effect_completed invokeStatic "events.clj" 244]
  [game.core$effect_completed invoke "events.clj" 240]
  [game.core$trigger_event_sync$fn__4974 invoke "events.clj" 65]
  [game.core$effect_completed invokeStatic "events.clj" 244]
  [game.core$effect_completed invoke "events.clj" 240]
  [game.core$trigger_event_sync_next invokeStatic "events.clj" 53]
  [game.core$trigger_event_sync_next doInvoke "events.clj" 40]
  [clojure.lang.RestFn applyTo "RestFn.java" 157]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 587]
  [game.core$trigger_event_sync invokeStatic "events.clj" 64]
  [game.core$trigger_event_sync doInvoke "events.clj" 55]
  [clojure.lang.RestFn applyTo "RestFn.java" 151]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 660]
  [game.core$resolve_trash invokeStatic "rules.clj" 315]
  [game.core$resolve_trash doInvoke "rules.clj" 311]
  [clojure.lang.RestFn invoke "RestFn.java" 500]
  [clojure.lang.AFn applyToHelper "AFn.java" 171]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 587]
  [game.core$trash invokeStatic "rules.clj" 349]
  [game.core$trash doInvoke "rules.clj" 319]
  [clojure.lang.RestFn invoke "RestFn.java" 500]
  [game.core$trash invokeStatic "rules.clj" 322]
  [game.core$trash invoke "rules.clj" 319]
  [game.core$move_card invokeStatic "actions.clj" 90]
  [game.core$move_card invoke "actions.clj" 61]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 145]
  [game.main$handle_command invoke "main.clj" 134]
  [game.main$run$fn__27971 invoke "main.clj" 180]
  [game.main$run invokeStatic "main.clj" 170]
  [game.main$run invoke "main.clj" 164]
  [game.main$_main$fn__28006 invoke "main.clj" 234]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by JoelCFC25** [comment] 2017-03-16 02:29
Duplicate of #2430. Fix is done and coming shortly.

**Closed by JoelCFC25** 2017-03-16 02:29 UTC
