### ISSUE TITLE
Obelus Access Bug - Major?

### ISSUE THREAD

**Issue by rosenthald** [mtgred/netrunner#2092] opened 2016-10-15 03:27 UTC
Obelus has a MAJOR bug in which if the runner chooses to access an upgrade in R&D or HQ before other cards, while he/she still draws the right number of cards, he doesn't get to access ANY cards (neither from HQ&RND or Upgrades). 

Noticed this in a couple games now. I thought it had to do with a weird interaction with Crisium, but it also happened when the runner had a Surat City Grid in HQ.

**Comment by JoelCFC25** [comment] 2016-10-15 03:34
I can't reproduce this on a couple initial attempts. Did you have any multi-access (Nerve Agent, Medium, et al)? Precisely what were all the upgrades present?

**Comment by rosenthald** [comment] 2016-10-15 03:35
Yeah, sorry. I had a Nerve Agent up on both attempts. First time it happened with Crisium, second with Surat City.

**Comment by rosenthald** [comment] 2016-10-15 03:36
Also, with Edward Kim, if that matters. But I don't think it ever got to the access anyway.

**Comment by JoelCFC25** [comment] 2016-10-15 03:57
Still no luck yet, ran HQ with a loaded Nerve Agent, accessed an unrezzed Crisium Grid first, got all the accesses I was supposed to and Obelus drew up at the end. Will keep trying...

**Comment by rosenthald** [comment] 2016-10-15 04:03
Thanks, sorry this is being frustrating to reproduce. Please let me know if I can do anything help.

**Comment by zaroth** [comment] 2016-10-15 05:58
Anything? Open a separate browser (e.g. in private mode) with jinteki.net, and play against yourself with a second account to try and get clear reproduction steps :)

You can also use the test server, jinteki.zaroth.net for this purpose if you want - it's the test server after all.

**Comment by nealterrell** [comment] 2016-10-15 18:21
There is a known issue with accessing REZZED upgrades in HQ that is fixed in #2064, which has not been deployed.

**Closed** 2016-10-22 19:19 UTC
Labels: bug
