### ISSUE TITLE
Guri davinder fires and trashes itself on obokata steal.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2848] opened 2017-10-07 05:03 UTC
![image](https://user-images.githubusercontent.com/18687557/31304903-7f0b8594-aaea-11e7-9bdd-f432a3bcc673.png)

**Comment by JoelCFC25** [comment] 2017-10-07 13:47
The `:pre-damage` event occurs before the check of whether or not the damage is unpreventable.

**Comment by nealterrell** [comment] 2017-10-10 16:14
Can probably pass the unpreventable parameter to pre-damage and have Guru incorporate that into its req.

**Comment by Saintis** [comment] 2017-10-12 13:42
What's the ruling on Guru + Obokata? Doesn't it both prevent damage and steal when you try to steal Obokata? Or are additional costs unpreventable?

**Comment by JoelCFC25** [comment] 2017-10-12 14:05
If you prevent the damage, you haven't taken it, thus cannot steal. So if you do elect to pay the additional cost, the damage functionally has to be unpreventable.

**Comment by Saintis** [comment] 2017-10-12 14:08
I was under the impression with Guru you had to access the Obokata twice, first to prevent the damage and trash Guru and then to actually take the damage and steal the agenda. If that's how the cards interact then this is working as intended (other than the fact that the damage _is_ applied).

**Comment by nealterrell** [comment] 2017-10-12 14:31
I think I'm with Saintis on this. You elect to pay the cost, Guru fires, so you can't steal. Is there a ruling anywhere?

**Comment by Saintis** [comment] 2017-10-12 14:39
Jakodrako has weighed in on the discussion regarding this interaction on Reddit: https://www.reddit.com/r/Netrunner/comments/6rkucy/does_guru_davinder_prevent_scoring_obokata/

I would count that as a ruling.

**Comment by JoelCFC25** [comment] 2017-10-12 14:40
Not the first time I've been wildly off base

**Comment by DeepSpawn** [comment] 2018-03-14 20:44
Given the ruling it sounds like this is working as intended, should we close off this issue?

**Comment by danhut** [comment] 2018-04-01 22:00
Fixed via #2985

**Closed by danhut** 2018-04-01 22:00 UTC
Labels: bug, cards
