### ISSUE TITLE
Undoing a runner event click results in the event being stuck in the temp play zone.

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5362] opened 2020-11-09 14:42 UTC
can be fixed by corp dragging the event back to runner hand.

**Comment by NoahTheDuke** [comment] 2020-11-09 17:19
I can't reproduce this. Do you have specific steps to make this happen?

**Comment by tolaasin** [comment] 2020-11-09 18:49
tolaasin started their turn 8 with 10  and 3 cards in their Grip.
tolaasin spends  to make a run on HQ.
tolaasin approaches Akhet protecting HQ at position 0.
tolaasin encounters Akhet protecting HQ at position 0.
tolaasin pays 2  to increase the strength of Paperclip to 3 and break all subroutines on Akhet.
tolaasin has no further action.
tolaasin passes Akhet protecting HQ at position 0.
tolaasin approaches HQ.
Derschef21 has no further action.
tolaasin uses Paragon to gain 1  and look at the top card of Stack.
tolaasin does not add the top card of the Stack to the bottom.
tolaasin accesses Audacity from HQ.
tolaasin places a power counter on The Turning Wheel.
tolaasin spends  to make a run on HQ.
tolaasin approaches Akhet protecting HQ at position 0.
tolaasin encounters Akhet protecting HQ at position 0.
tolaasin pays 2  to increase the strength of Paperclip to 3 and break all subroutines on Akhet.
tolaasin has no further action.
tolaasin passes Akhet protecting HQ at position 0.
tolaasin approaches HQ.
Derschef21 has no further action.
tolaasin accesses Dedication Ceremony from HQ.
tolaasin places a power counter on The Turning Wheel.
tolaasin spends  to make a run on HQ.
tolaasin approaches Akhet protecting HQ at position 0.
tolaasin encounters Akhet protecting HQ at position 0.
tolaasin pays 2  to increase the strength of Paperclip to 3 and break all subroutines on Akhet.
tolaasin passes Akhet protecting HQ at position 0.
tolaasin approaches HQ.
Derschef21 has no further action.
tolaasin accesses Audacity from HQ.
tolaasin places a power counter on The Turning Wheel.
tolaasin spends  and pays 2  to play Inside Job.
tolaasin approaches Guard protecting R&D at position 0.
tolaasin encounters Guard protecting R&D at position 0.
tolaasin uses Inside Job to bypass Guard.
tolaasin
tolaasin
sorry
!tolaasin uses a command: /undo-click
!tolaasin uses a command: /undo-click
tolaasin
tolaasin
won't come back to hand
Derschef21
Derschef21
u need to pull it back
tolaasin
tolaasin
right
tolaasin
tolaasin
but it won't
Derschef21 moves a card to Grip.
tolaasin has left the game.
tolaasin rejoined the game.
tolaasin
tolaasin
It's broken
tolaasin
tolaasin
can't install cards
!Derschef21 uses a command: /undo-turn
!tolaasin uses a command: /trash
tolaasin spends  and pays 4  to install The Class Act.

**Comment by tolaasin** [comment] 2020-11-09 18:50
it's happened twice to me today. both time it was a run event on R&D>

**Comment by lallmon** [comment] 2021-05-09 17:59
@NoahTheDuke I've seen this 3 or 4 times, specifically with Overclock and Tread Lightly. Just play it, pick a server, then `/undo-click`

You'll wind back everything, but the card will stay in the play area, which you have to drag back to your grip. Not the end of the world, but I didn't know you could drag cards for the longest time. :D

I'll try to get full repro steps next time I'm in my dev environment.

**Comment by NoahTheDuke** [comment] 2021-05-09 19:06
No worries, the reason and solution are known, just hard to implement. Will be fixed when action windows are enforced.

**Comment by francescopellegrini** [comment] 2023-10-08 13:04
@NoahTheDuke fixed already.

**Closed** 2023-10-08 14:31 UTC
Labels: bug, game interface, engine
