### ISSUE TITLE
While rezzing draco the power counters prompt window appears twice

### ISSUE THREAD

**Issue by Jherek** [mtgred/netrunner#254] opened 2015-06-16 08:14 UTC
To see it:
Install Draco
Rez Draco
Appears the prompt (how many power counters do you want on it?). Click any.
Draco is rezzed, but the Prompt (how many power counters do you want on it?) persists.
If you select any power counter (even 0), draco is unrezzed, but it's the only way to get rid of the prompt.

**Comment by Astrochelys** [comment] 2015-06-17 04:16
I had the exact same problem in all the instances i played draco today.

**Comment by nealterrell** [comment] 2015-06-17 16:47
This could be related to #252, since both involve showing a prompt on rez.

**Comment by mtgred** [comment] 2015-06-23 16:11
A fix has been deployed this morning. It should work correctly now.

**Comment by JoelCFC25** [comment] 2015-06-29 14:34
Confirmed that this one is fixed by 009acdbea0b81d90d64c6eec9f832054e1631e69. @Jherek you can close it out. :+1:

**Closed** 2015-06-29 14:44 UTC
