### ISSUE TITLE
Marjanah's cost reduction for breaking a subroutine is not applied correctly

### ISSUE THREAD

**Issue by garlic-runner** [mtgred/netrunner#5890] opened 2021-05-17 02:09 UTC
If you watch the replay, I test this several times. After a successful run on HQ, the cost reduction is applied correctly if I try to break one subroutine at a time.

```
generic pays 1  to use Marjanah to break 1 Barrier subroutine on Pharos (" Give the Runner 1 tag").
generic pays 4  to use Marjanah to break the remaining 2 subroutines on Pharos.
```
However if I try to break the remainine subroutines together, I get charged 2 credits each.

```
generic pays 4  to increase the strength of Marjanah to 5.
generic pays 6  to use Marjanah to break all 3 subroutines on Pharos.
```

Also the Jinteki doesn't seem to understand the subroutines are broken and forces me to end the run. Here's a link to the replay file:

https://www.jinteki.net/replay/7b8e3ddd-b346-4c40-a037-028cc8a19574

Additionally here are some screenshots that show how the UI is affected:

https://media.discordapp.net/attachments/715673394762350622/843665451401609267/Screen_Shot_2021-05-16_at_9.44.47_PM.jpg?width=1650&height=942

https://media.discordapp.net/attachments/715673394762350622/843665903950364692/Screen_Shot_2021-05-16_at_9.46.55_PM.jpg

Hope this helps!

**Comment by garlic-runner** [comment] 2021-05-17 02:11
Also here's a link to the timestamp at the end of the replay where I found the bug: https://www.jinteki.net/replay/7b8e3ddd-b346-4c40-a037-028cc8a19574?n=80&d=3

**Comment by francescopellegrini** [comment] 2021-05-18 12:36
Duplicate of #5736?

**Comment by NoahTheDuke** [comment] 2021-05-18 13:57
Thanks for the report! Yes, this is a duplicate. Closing in favor of the other one.

**Closed by NoahTheDuke** 2021-05-18 13:57 UTC
Labels: bug, card, duplicate, engine
