### ISSUE TITLE
Runner accessing Increased Drop Rates triggers odd text 

### ISSUE THREAD

**Issue by willybn1** [mtgred/netrunner#6707] opened 2022-11-05 05:02 UTC
no biggie this one ....

![image](https://user-images.githubusercontent.com/36125436/200102046-cc984ef1-6b8f-4c1f-b8a4-8dbb41acaf53.png)

**Comment by willybn1** [comment] 2022-11-05 05:09
also,should say that the first time runner accessed this i had no Bad Pub, i got the weird text update and Drop Rates gave him a tag but that was not captured in text. the second time runner accessed the Drop Rate it did not give a tag but got weird text (from an alien race trying to contact us maybe? what have we unleashed?)

![image](https://user-images.githubusercontent.com/36125436/200102249-0beda7ac-5723-4045-a784-fb13535363bb.png)

**Comment by francescopellegrini** [comment] 2022-12-03 10:49
I cannot reproduce it using the latest version of the code (not yet released)

**Comment by francescopellegrini** [comment] 2023-01-02 15:31
Might as well close this.

**Closed** 2023-01-02 16:30 UTC
