### ISSUE TITLE
Ken "Express" Tenma - Influence Increase Not Detected

### ISSUE THREAD

**Issue by Sontail** [mtgred/netrunner#1595] opened 2016-06-08 03:04 UTC
In the deck editor, it does not compensate for Tenma's 17 Influence and detects a deck with his ID above the usual 15 influence as Casual Play Only.

**Comment by nealterrell** [comment] 2016-06-08 03:35
Can you post a screenshot of your deck? I am not seeing this issue:

![image](https://cloud.githubusercontent.com/assets/10083341/15881961/62939cb4-2cef-11e6-9983-96911cf44ce7.png)

**Comment by Sontail** [comment] 2016-06-08 03:40
I'm still new to the deckbuilder but this is what I come up with:
[image: Tenma Bug.png]

**Comment by queueseven** [comment] 2016-06-08 09:01
@Sontail Sorry, we can't see your image. Maybe you can upload it over the github website directly instead of sending an email?

**Comment by JoelCFC25** [comment] 2016-06-29 14:46
@Sontail: I am going to close this unless since it can't be reproduced. Make sure you were not using cards from the [Most Wanted List](http://ancur.wikia.com/wiki/Category:NAPD_Most_Wanted_List), which effectively reduce available influence in any ID other than The Professor.

**Closed by JoelCFC25** 2016-06-29 14:46 UTC
Labels: can't reproduce
