### ISSUE TITLE
Fully Operational does not tell what corp do in console

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4141] opened 2019-03-21 22:19 UTC
Fully Operational does not tell what corp do in console as you can see here 
![image](https://user-images.githubusercontent.com/1651150/54788554-b37d0680-4c2f-11e9-9775-b9b325eb6cf0.png)

**Comment by NoahTheDuke** [comment] 2019-03-22 14:12
Duplicate of #4102

**Closed** 2019-03-28 14:50 UTC
Labels: bug, duplicate
