### ISSUE TITLE
BUGS: Vamp, Account Siphon

### ISSUE THREAD

**Issue by benticurus** [mtgred/netrunner#162] opened 2015-04-22 17:44 UTC
Vamp BUG: it takes double the credits from what the runner actually pays (e.g., if the runner pays 10 credits to Vamp the corp, the runner ends up loosing 20 credits).

Account Siphon BUG: sometimes gives the runner double the credits and tags

**Comment by mtgred** [comment] 2015-04-23 19:47
Vamp has been fixed.

I can't reproduce the Account Siphon issue but will continue to investigate the issue.

**Comment by eah13** [comment] 2015-05-19 11:00
@mtgred I wonder if the Account Siphon double creds is related to a more general bug of some things happening twice.  I've noticed sometimes a turn will start twice, giving the corp two cards or the runner 4c from Daily Casts.  I can't tell what's causing it or how to reproduce but suspect a general bug like that could be behind this.

**Comment by JoelCFC25** [comment] 2015-08-30 19:02
Is this still happening with any regularity for anyone?

**Comment by queueseven** [comment] 2015-08-30 19:52
I've played a lot of Vamp and Siphon (yeah, I'm a  bad person) and I never noticed this, and also not with other cards

**Comment by JoelCFC25** [comment] 2015-09-01 15:19
Let's close this for now. If it becomes more widespread we can reopen the issue.

**Closed by JoelCFC25** 2015-09-01 15:19 UTC
Labels: can't reproduce
