### ISSUE TITLE
Getting error while playing

### ISSUE THREAD

**Issue by rilunan** [mtgred/netrunner#2418] opened 2017-03-14 16:08 UTC
Please describe the circumstances of your error here.

Stack Trace:
```clojure
Error do play Personal Workshop #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Numbers ops "Numbers.java" 1013]}]
 :trace
 [[clojure.lang.Numbers ops "Numbers.java" 1013]
  [clojure.lang.Numbers isZero "Numbers.java" 92]
  [game.core$fn__10081 invokeStatic "assets.clj" 367]
  [game.core$fn__10081 invoke "assets.clj" 367]
  [game.core$trigger_event invokeStatic "events.clj" 36]
  [game.core$trigger_event doInvoke "events.clj" 27]
  [clojure.lang.RestFn invoke "RestFn.java" 494]
  [game.core$runner_install invokeStatic "installing.clj" 323]
  [game.core$runner_install invoke "installing.clj" 310]
  [game.core$play invokeStatic "actions.clj" 17]
  [game.core$play invoke "actions.clj" 11]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 145]
  [game.main$handle_command invoke "main.clj" 134]
  [game.main$run$fn__27373 invoke "main.clj" 180]
  [game.main$run invokeStatic "main.clj" 170]
  [game.main$run invoke "main.clj" 164]
  [game.main$_main$fn__27408 invoke "main.clj" 234]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by danhut** [comment] 2017-03-16 05:56
Was Docklands Crackdown in play?

Looks like a Duplicate of #2419 if so - which will be resolved in the next code push.

**Closed** 2017-04-08 02:57 UTC
