### ISSUE TITLE
Floating prompt after Paladin trigger

### ISSUE THREAD

**Issue by tanderson11** [mtgred/netrunner#4790] opened 2019-12-18 20:26 UTC
If the runner has a Paladin companion with 3 credits on it at the end of the turn, they must either trash an installed card or trash Paladin. If they trash another installed card, the corp is stuck waiting on a prompt even after the runner has resolved the action.

**Comment by NoahTheDuke** [comment] 2019-12-18 23:41
Thanks for the report!

**Comment by lostgeek** [comment] 2019-12-19 12:37
Duplicate of #4784

**Closed** 2019-12-20 00:40 UTC
Labels: bug, card
