### ISSUE TITLE
Miss Bones gives an additional credit after use

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4410] opened 2019-08-16 10:02 UTC
Consistently saw an additional message in the console 'runner gains 1c for using Miss Bones' after they had taken the correct number of credits off it to trash an asset. This was against Gagarin with Paywall out.

**Comment by NoahTheDuke** [comment] 2019-08-16 14:41
Do you have a screenshot or more information? Did the runner use the "pay-credits"/recurring credits prompt? Or did they pay out of pocket, and then click on Miss Bones after the fact?

**Comment by lostgeek** [comment] 2019-08-17 22:56
Happened to my opponent on a Core Experience + R&R game as well with little other cards involved.

**Comment by NoahTheDuke** [comment] 2019-08-17 23:28
Huh, that's weird.

**Comment by tolaasin** [comment] 2019-08-19 08:58
I don't Noah, I'm afraid. I should capture more from the chat when I report bugs. Part of the challenge with Miss Bones is you don't know what the runner is clicking on when they use her.

**Comment by FarCryFromHuman** [comment] 2019-08-20 02:53
Probably a weird place for this suggestion, but maybe when a payment is complete, it should print what cards and how many of their credits were used to pay, in the same way it lists normal credits, clicks, etc. I know you recently revamped payments in general, so this seems more feasible than ever.

**Comment by NoahTheDuke** [comment] 2019-08-20 10:18
It already does that!

**Comment by tolaasin** [comment] 2019-08-28 16:47
so I think that this is because the runner took too many credits off miss bones for the trash, and it's reporting the overage in the chat?

**Comment by ouroboros8** [comment] 2019-10-05 11:49
I've just had a look at this and I suspect the problem is that if you mash Miss Bones when the "take credits off a card" prompt is up, it's easy to click too many times, at which point the manual click function of miss bones kicks in and you take a credit.

I think a reasonable fix for this is to put the manual credit removal on miss bones behind a menu, so that if you accidentally click too many times the menu is opened instead of a credit being taken immediately.

**Closed** 2019-10-06 21:11 UTC
Labels: bug, card
