### ISSUE TITLE
 rezzed Blacklist does not prevent Ark Lockdown

### ISSUE THREAD

**Issue by pCox532** [mtgred/netrunner#2214] opened 2016-12-12 12:07 UTC
Blacklist should prevent cards from leaving the heap, but Ark Lockdown still removes the chosen card from the game.

**Comment by JoelCFC25** [comment] 2016-12-12 12:48
Thanks--this is a duplicate of #1946. I'll add Ark Lockdown to that issue and we'll track progress there.

**Closed by JoelCFC25** 2016-12-12 12:48 UTC
Labels: bug, duplicate
