### ISSUE TITLE
Chakana

### ISSUE THREAD

**Issue by Greyhead92** [mtgred/netrunner#1286] opened 2016-02-26 18:47 UTC
Hello,
Chakana always reduce the advancement requirement of all agendas by 1. Even without virus counters on it..

regards,
Greyhead

**Comment by JoelCFC25** [comment] 2016-02-26 19:07
I can't reproduce this. Are you sure there were no other cards in play that could have factored in--e.g., Hivemind, The Source, Traffic Jam?

**Comment by nealterrell** [comment] 2016-02-26 19:19
Was there a purge involved? I can see how a purge wouldn't cause Chakana to recalculate advancement requirements for currently-installed agendas.

**Comment by Greyhead92** [comment] 2016-02-26 19:28
there could be a purge involved... had the mistake 2 times in 2 different games by my opponents

**Comment by glass4pk** [comment] 2016-02-27 03:54
take a picture?

**Comment by JoelCFC25** [comment] 2016-03-16 14:27
I'm going to close this for now. If anyone can come up with reproduction steps we'll revisit it.

**Closed by JoelCFC25** 2016-03-16 14:27 UTC
Labels: can't reproduce, cards
