### ISSUE TITLE
Deleting the wrong deck

### ISSUE THREAD

**Issue by erbridge** [mtgred/netrunner#1998] opened 2016-09-24 19:02 UTC
In the deckbuilder, if you press delete, then select another deck and then confirm the deletion, the currently selected deck is deleted. Probably selecting another deck should cancel the deletion.

**Comment by nealterrell** [comment] 2016-09-24 19:38
Duplicate of #1364. Thanks though :).

**Closed by nealterrell** 2016-09-24 19:38 UTC
