### ISSUE TITLE
Recronstruction Contract #21020 triggers also on Net-Damage...

### ISSUE THREAD

**Issue by ANR-PeterPan** [mtgred/netrunner#3068] opened 2018-02-09 22:14 UTC
... also its "may", so perhaps a prompt to ask?
See below
![image](https://user-images.githubusercontent.com/24223024/36052578-8dc1d61c-0dee-11e8-8bdc-b99ed132c505.png)

**Comment by nealterrell** [comment] 2018-02-10 02:08
Thanks. We'll keep it automatic until there is a valid reason to not want the counter.

**Comment by nealterrell** [comment] 2018-02-12 00:17
Duplicate of #2982.

**Closed by nealterrell** 2018-02-12 00:17 UTC
