### ISSUE TITLE
ID Swap Issue

### ISSUE THREAD

**Issue by ichigokuto** [mtgred/netrunner#3822] opened 2018-07-28 13:23 UTC
bug.
Runner is Jesminder Sareen, with DJ Fenris installed, hosting Liza..
Runner stole an agenda
Corp has amani senai installed.
Corp bounces back fenris to hand.
Liza replaces the Jesminder ID.

**Comment by nealterrell** [comment] 2018-07-28 17:55
Duplicate of #3791.

**Closed by nealterrell** 2018-07-28 17:55 UTC
