### ISSUE TITLE
Deepdive into Bacterial programming freezes up game

### ISSUE THREAD

**Issue by Zerothmaxima** [mtgred/netrunner#6361] opened 2022-05-10 19:16 UTC
After the corp programs their bacterials, the runner gets an option button to resumer run and a greyed out button. Neither do anything and /close-prompt does not help. 

I assume there is a conflict with bacterial ordering R&D and DD shuffling?

**Comment by NBKelly** [comment] 2022-05-11 01:07
Duplicate of #6324

**Closed** 2022-05-11 15:58 UTC
