### ISSUE TITLE
Apocalypse and Hostile Infrastructure

### ISSUE THREAD

**Issue by NoxMortem** [mtgred/netrunner#3049] opened 2018-02-02 19:05 UTC
Apocalypse against Hostile Infrastructure caused a game error.

Please describe the circumstances of your error here.

Stack Trace:
```clojure
Error do choice Done #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [game.core$resolve_prompt invokeStatic "actions.clj" 150]}]
 :trace
 [[game.core$resolve_prompt invokeStatic "actions.clj" 150]
  [game.core$resolve_prompt invoke "actions.clj" 120]
  [game.main$handle_do invokeStatic "main.clj" 83]
  [game.main$handle_do invoke "main.clj" 79]
  [game.main$handle_command invokeStatic "main.clj" 152]
  [game.main$handle_command invoke "main.clj" 141]
  [game.main$run$fn__32896 invoke "main.clj" 201]
  [game.main$run invokeStatic "main.clj" 191]
  [game.main$run invoke "main.clj" 184]
  [game.main$_main$fn__32933 invoke "main.clj" 260]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 748]]}
```

**Comment by JoelCFC25** [comment] 2018-02-05 14:18
Duplicate of #1365.

**Comment by JoelCFC25** [comment] 2018-04-20 14:02
All hail @nicohasa, this works now.

**Closed by JoelCFC25** 2018-04-20 14:02 UTC
Labels: bug, cards, duplicate
