### ISSUE TITLE
Chairman Hiro incorrectly scored

### ISSUE THREAD

**Issue by MGillett** [mtgred/netrunner#4420] opened 2019-08-17 16:43 UTC
Runner scored a Bacterial Programming (from Archives, if I recall correctly). Corp triggered Bacterial Programming and used it to trash a Chairman Hiro from R&D. This resulted in Chairman Hiro being scored by the runner.

**Comment by NoahTheDuke** [comment] 2019-08-17 21:39
Duplicate of #3090

**Closed** 2019-08-19 16:58 UTC
