### ISSUE TITLE
Kakugo last ice and caprice nisei interaction bug.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2651] opened 2017-07-16 22:23 UTC
This causes kakugo net damage to not fire.
![image](https://user-images.githubusercontent.com/18687557/28251830-0089c416-6a43-11e7-9b43-d4dfb41d1c5e.png)

**Comment by JoelCFC25** [comment] 2017-07-17 01:28
Please check existing issues first--this is a duplicate of #2630 (which I haven't managed to reproduce yet).

**Closed** 2017-08-20 17:12 UTC
Labels: bug, cards, duplicate
