### ISSUE TITLE
NPE trying to install Symmetrical Visage

### ISSUE THREAD

**Issue by ilyanep** [mtgred/netrunner#2134] opened 2016-11-02 00:22 UTC
Playing an arena game, trying to install baby, got this error ?:|

Stack Trace:
```clojure
Error do play Symmetrical Visage #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Numbers ops "Numbers.java" 1013]}]
 :trace
 [[clojure.lang.Numbers ops "Numbers.java" 1013]
  [clojure.lang.Numbers gt "Numbers.java" 229]
  [game.core$has_most_faction_QMARK_$reducer__15829 invoke "identities.clj" 19]
  [clojure.core$fn__6939$fn__6941 invoke "core.clj" 6557]
  [clojure.core.protocols$iter_reduce invokeStatic "protocols.clj" 49]
  [clojure.core.protocols$fn__6742 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__6742 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__6684$G__6679__6697 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6545]
  [clojure.core$fn__6939 invokeStatic "core.clj" 6547]
  [clojure.core$fn__6939 invoke "core.clj" 6547]
  [clojure.core.protocols$fn__6763$G__6758__6772 invoke "protocols.clj" 174]
  [clojure.core$reduce_kv invokeStatic "core.clj" 6573]
  [clojure.core$reduce_kv invoke "core.clj" 6564]
  [game.core$has_most_faction_QMARK_ invokeStatic "identities.clj" 24]
  [game.core$has_most_faction_QMARK_ invoke "identities.clj" 9]
  [game.core$fn__16160 invokeStatic "identities.clj" 315]
  [game.core$fn__16160 invoke "identities.clj" 315]
  [game.core$trigger_event invokeStatic "events.clj" 36]
  [game.core$trigger_event doInvoke "events.clj" 27]
  [clojure.lang.RestFn invoke "RestFn.java" 467]
  [game.core$runner_install invokeStatic "installing.clj" 310]
  [game.core$runner_install invoke "installing.clj" 297]
  [game.core$play invokeStatic "actions.clj" 17]
  [game.core$play invoke "actions.clj" 11]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 150]
  [game.main$handle_command invoke "main.clj" 139]
  [game.main$run$fn__25323 invoke "main.clj" 185]
  [game.main$run invokeStatic "main.clj" 175]
  [game.main$run invoke "main.clj" 169]
  [game.main$_main$fn__25358 invoke "main.clj" 239]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by ilyanep** [comment] 2016-11-02 00:24
FWIW playing the green arena ID that lets me draw a card when i install and this was my first install of the turn

**Comment by JoelCFC25** [comment] 2016-11-02 01:19
Duplicate of #2112

**Closed** 2016-11-06 19:11 UTC
Labels: bug, duplicate
