### ISSUE TITLE
Ice not trashed on Spooned run if painted but not broken with Engolo

### ISSUE THREAD

**Issue by anarchomushroom** [mtgred/netrunner#5877] opened 2021-05-10 23:59 UTC
On a run with Spooned, I used Engolo to make a Karuna on RnD a code gate, but used an MKUltra to break it (as it was both a sentry and code gate). It didn't trash however despite matching the conditions for Spooned.

![image](https://user-images.githubusercontent.com/52526629/117738534-2a9cfc80-b1f4-11eb-9d28-9c9ec7fb8219.png)

**Comment by NoahTheDuke** [comment] 2021-05-11 00:55
Thanks for the report!

**Comment by francescopellegrini** [comment] 2021-05-15 19:01
Duplicate of #5842?

**Comment by NoahTheDuke** [comment] 2021-05-17 14:00
Yes, I think so.

**Comment by francescopellegrini** [comment] 2023-01-02 15:36
Might as well close this.

**Closed** 2023-01-02 16:15 UTC
Labels: bug, duplicate, card, engine
