### ISSUE TITLE
Ob doesn't ignore Tread Lightly cost

### ISSUE THREAD

**Issue by cfreyvogel** [mtgred/netrunner#7214] opened 2023-11-14 16:01 UTC
Link to bug replay: https://jinteki.net/bug-report/b0f533ab-1486-42be-aa16-1ebc77eff123?b=0

Description:

Reina Roja ran against a server with border control using Tread Lightly. Rezzed the BC, paying the extra 3. Let the runner past 2 more unrezzed ICE before firing BC and getting Sandstone. Was forced to pay the extra 3 from Tread Lightly while Ob should ignore credit costs to rez.

**Comment by butzopower** [comment] 2023-11-14 19:00
Duplicate of #6824

**Closed** 2023-11-14 19:58 UTC
