### ISSUE TITLE
Parasite Bug

### ISSUE THREAD

**Issue by benticurus** [mtgred/netrunner#242] opened 2015-06-11 10:28 UTC
When ICE that is already at 0 strength gets Parasited, the Parasite card disappears immediately from game after destroying the ICE. E.g., if you Parasite a Quandary, the QUandary gets destroyed, but the Parasite disappears (plus I also couldn't play other Parasite from my hand afterwards, even though I had enough credits and memory to play it).

**Comment by JoelCFC25** [comment] 2015-06-11 14:15
I think this is a duplicate of #214.

**Comment by nealterrell** [comment] 2015-06-11 14:19
Thanks for the report, we have a fix in testing that will hopefully be deployed soon.

**Comment by mtgred** [comment] 2015-06-12 14:22
Thanks for reporting the issue. The Parasite code automating the ICE trashing was quite buggy and caused all sorts of problem. It has been removed so now the ICE has be trashed manually. But at least there shouldn't be ill effects anymore.

**Comment by mkcontra** [comment] 2015-06-13 01:45
Running into something similar with the same Argus deck 3 times now. It hangs after an ice is trashed or an Agenda is stolen. Runner sees greyed "continue or jack out" and Corp gets a "no further action" option that clicks and then hangs.

**Comment by thesm17** [comment] 2015-06-16 18:13
I'm not sure if this is the same bug (probably not) but I've had some trouble with parasite on Little Engine. A parasite was installed on my LE, and after that no counters for that parasite or one on another ice appeared. Then when that LE was spooned, I tried dragging the LE to the trash, and it froze the game. Not sure what else to say.

**Comment by JoelCFC25** [comment] 2015-07-06 19:07
I can't replicate the Argus error or the Parasite on Little Engine problem. The code for Parasite was improved recently, so I think this one is fixed.

**Closed by JoelCFC25** 2015-07-06 19:07 UTC
Labels: can't reproduce
