### ISSUE TITLE
Boi-tatá cannot break subs anymore if a runner card was trashed that turn

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#7409] opened 2024-05-01 08:55 UTC
Boi-tatá break-subs ability works fine if no Runner cards were trashed that turn, but cannot be used otherwise 🤷 

EDIT: I'm experiencing this while running jnet locally

**Comment by NBKelly** [comment] 2024-06-29 22:58
Duplicate of #7360

**Closed** 2024-07-01 07:12 UTC
Labels: bug
