### ISSUE TITLE
Laramy Fisk's ID ability puts up a steal window which you can't resolve

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#707] opened 2015-09-12 04:15 UTC
Replication steps:
1. Create a game and have the corp end their turn with 2 agendas at the top of their deck
2. On runners turn Run R & D, succeed and force corp to draw card
3. Get stuck on steal window that can't resolve

**Comment by queueseven** [comment] 2015-09-12 05:32
Duplicate of https://github.com/mtgred/netrunner/issues/515

**Comment by nealterrell** [comment] 2015-09-14 03:04
We are working on this... the current idea is a manual workaround, where runner clicks on Fisk prior to hitting "Successful Run" to force the draw. A full automation will require a lot of engine work down the line.

**Closed** 2015-09-19 18:29 UTC
Labels: bug, duplicate
