### ISSUE TITLE
Marilyn recycling considered "adding a card to archives" for Regenesis

### ISSUE THREAD

**Issue by elimeckler** [mtgred/netrunner#7614] opened 2024-08-07 04:22 UTC
Link to bug replay: https://jinteki.net/bug-report/34212528-7176-4ea6-bad0-29ef63e7e848?b=0

Description: Marilyn Campagin recycle disables Regenesis

1. Have Holo Man on Marilyn Campaign, facedown agenda in archives, and Regenesis in HQ 
2. Install Regenesis on Holo Man, overwriting the Marilyn, but shuffle Marilyn back into R&D instead of trashing it (according to card text, this is instead of adding it to Archives)
3. FA the Regenesis 

Desired behavior: should be prompted to add facedown agenda to score area

Observed behavior: no prompt

**Comment by NBKelly** [comment] 2024-08-10 02:12
Duplicate of #6895

**Closed** 2024-08-10 15:21 UTC
