### ISSUE TITLE
Paperclip not triggering on Snowflake

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2036] opened 2016-10-03 10:15 UTC
Paperclip in the bin, encountered Snowflake (the psi ice), no prompt to install from the bin.

**Comment by nealterrell** [comment] 2016-10-04 03:10
Do you happen to remember how Paperclip ended up in the heap?

**Comment by tolaasin** [comment] 2016-10-04 06:45
Trashed at end of turn.

**Comment by JoelCFC25** [comment] 2016-10-04 13:21
I'm not able to reproduce this in development yet--doesn't seem to matter if Paperclip hits the Heap by manual trashing, being taken from damage, etc.

**Comment by tolaasin** [comment] 2016-10-04 13:35
It happened twice in the same game, but likely we have to just write this off to experience if it's not reproducible.

**Comment by JoelCFC25** [comment] 2016-10-04 13:37
Let's see where things stand later (hopefully today) when the multi-access bug is fixed.

**Comment by JoelCFC25** [comment] 2016-10-07 16:10
How's it going with Paperclip (and now Black Orchestra, since they do the same kind of thing)?

**Comment by JoelCFC25** [comment] 2016-10-21 20:13
Closing due to lack of confirmation and no further reports.

**Closed by JoelCFC25** 2016-10-21 20:13 UTC
Labels: bug, can't reproduce, cards
