### ISSUE TITLE
Film Critique / Haapsichord studio issue

### ISSUE THREAD

**Issue by mtgred** [mtgred/netrunner#624] opened 2015-08-27 18:40 UTC
See game log in screenshot.

In Archives: Restructure, Hedge Fund, TGBT

![screen shot 2015-08-27 at 20 36 20](https://cloud.githubusercontent.com/assets/284114/9529648/be853732-4cfb-11e5-89ce-873cfc962c7e.png)

**Comment by nealterrell** [comment] 2015-08-31 04:23
I can't reproduce this :(. I'll keep an eye out, but I tried what I see pictured here:

1. Runner has already stolen something this turn (so he can't steal the first Explode-a accessed.
2. Runner runs Archives with 2 Explode-a and TGTBT. 
3. Runner accesses Explode-a, cannot steal, says OK. (No further log message.)
4. Accesses second Explode-a, cannot steal, uses Film Critic. (Log message for Critic.)
5. At this point in my testing, I am able to access TGTBT, which prints a log (gives runner 1 tag) and says I can't steal. Click OK, run ends.

The log here shows TGTBT being accessed, but doesn't show the tag being applied, which is weird.  I'm thinking there's some other crashing issue but don't know what it is. I'll let you know.

**Comment by JoelCFC25** [comment] 2016-01-07 17:00
Closing this one. I tested it now and it all works:

1. Runner steals the first Explode-a (Corp gets the 5c)
2. Runner hosts the second Explode-a on Film Critic (Corp gets the 5c)
3. Runner can't steal the TGTBT but takes the tag

**Closed by JoelCFC25** 2016-01-07 17:00 UTC
Labels: bug, can't reproduce
