### ISSUE TITLE
SYNC BRE's 2nd subroutine does not work on remote servers

### ISSUE THREAD

**Issue by manveruppd** [mtgred/netrunner#5014] opened 2020-03-11 16:29 UTC
subroutineTrace [2]– If successful, the Runner accesses 1 fewer card whenever he or she accesses cards for the remainder of this run.

We played a game on Zaroth yesterday in which a SYNC BRE was installed on a remote server with a single card installed in it. I ran it, it fired, I couldn't beat the trace, but when I got to the bottom of the server it let me access the installed agenda anyway. 

I'm afraid I did not take a screenshot

**Comment by NoahTheDuke** [comment] 2020-03-11 18:23
Thanks for the report! I believe this is a known issue, but I'm glad for the reminder to actually fix it.

**Comment by NoahTheDuke** [comment] 2020-03-11 18:24
Looks like this is a duplicate of #4845

**Closed** 2020-04-08 05:49 UTC
Labels: bug, card, duplicate, engine
