### ISSUE TITLE
Rejig doesn't apply correct discount

### ISSUE THREAD

**Issue by Kenneth-Siu** [mtgred/netrunner#4152] opened 2019-03-24 14:29 UTC
I suppose this is what #4105 is referring to?

Start a game with any ID, not just Kabonesa Wu.

1. Install Engolo (go to 0 credits).
2. Play Rejig on Engolo. It doesn't let you install Engolo again.
3. Manually gain some credits, and Rejig will let you install Engolo for 3 credits. (Should be 0 credits. 5 cost, with a discount of 5 from Rejig)

![image](https://user-images.githubusercontent.com/8361722/54880811-29a48780-4e41-11e9-97a0-b611a142479e.png)

**Comment by NoahTheDuke** [comment] 2019-03-24 15:35
Indeed it is! Thanks for the report! This is a duplicate of the issue you mentioned, but I’ll leave it up so others can reference it

**Closed** 2019-04-10 20:03 UTC
Labels: bug, cards, duplicate
