### ISSUE TITLE
Cutlery Events Broken, Divide & Conquer + Black Hat HQ Access

### ISSUE THREAD

**Issue by whiterabbit1670** [mtgred/netrunner#3798] opened 2018-07-20 22:54 UTC
All 3 events; Knifed, Forked, and Spooned cause the game to lock up before the server to be run is chosen. This can only be fixed by /undo-turn, making the events useless.

When combining Black Hat + Divide & Conquer, the Archives and R&D accesses work fine, but all of HQ is accessed, regardless of the number of cards in HQ.

**Comment by jwarwick** [comment] 2018-07-20 23:51
Cutlery crash if fixed in #3794

**Comment by whiterabbit1670** [comment] 2018-07-27 19:32
Cutlery still not allowing choice of server to run. Prompt opens, but no choice can be made.

**Comment by NoahTheDuke** [comment] 2019-01-04 23:57
I'd love to see that log. I can't reproduce this.

**Closed** 2019-01-11 03:46 UTC
Labels: bug, can't reproduce
