### ISSUE TITLE
Hostile Infrastructure firing twice in a turn

### ISSUE THREAD

**Issue by mystermerry** [mtgred/netrunner#6910] opened 2023-02-24 08:29 UTC
Link to bug replay: https://jinteki.net/bug-report/43e30d43-87ce-4e77-8050-75f9a4a2c0d1?b=0

Description:

Overclock run on a remote server. Hostile Infrastructure rezzed in different server before access. Trashed asset using Overclock credits triggering Hostile Infrastructure.
Next run on remote with Hostile Infrastructure where it is trashed fires the effect a second time.

**Comment by francescopellegrini** [comment] 2023-03-01 11:50
Duplicate of #6897

**Comment by francescopellegrini** [comment] 2023-09-25 18:14
Fixed by #7120

**Closed** 2023-09-26 13:58 UTC
