### ISSUE TITLE
Surfer Interaction Broken

### ISSUE THREAD

**Issue by pajamieez** [mtgred/netrunner#5160] opened 2020-06-11 00:55 UTC
When surfer is used, the switch will happen once. The second time, the switch will not occur moving up the row. When switching back, chat will display that the position has changed, but the card will remain in the current position. 

Manual position switch by corp will duplicate the card in the ice stack and add an additional card.

**Comment by NoahTheDuke** [comment] 2022-08-02 02:52
Duplicate of #5145

**Closed by NoahTheDuke** 2022-08-02 02:52 UTC
