### ISSUE TITLE
Black File + Dr Lovegood

### ISSUE THREAD

**Issue by Rotage** [mtgred/netrunner#4057] opened 2019-03-05 20:26 UTC
Hi

The Black File - https://netrunnerdb.com/en/card/10099
Dr. Lovegood - https://netrunnerdb.com/en/card/09042

At present if Black File is blanked by Dr Lovegood while Black File has 0 counters and the corp then scores 7 points on their turn it results in a corp victory

It would appear that Dr Lovegood is blanking Blackfile for the runner turn and the corp turn when it should only be blank for the runner turn

**Comment by presheaf** [comment] 2019-03-13 11:00
I think the issue is that Black File only sets the `:cannot-win-on-points` flag when installed, meaning it's not set when re-enabled. As `enable-card` doesn't trigger the enabled card's play effect, (https://github.com/mtgred/netrunner/blob/master/src/clj/game/core/cards.clj#L311) Black File won't ever re-set the flag. 

To confirm, install Black File and Lovegood, pass turn back and forth, have Lovegood blank Black File, pass turn back and forth, then pass turn without having Lovegood blank Black File. I think the Corp will be able to win on points. 

If this is the case, this can be fixed by giving The Black File a `:reactivate` effect which sets the  `:cannot-win-on-points` flag, as Lovegood triggers this effect when re-enabling the card (https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/resources.clj#L746) . See DJ Fenris for an example of how this is used.

If you fix this bug, please also have a look at Lewi Guilherme, which I think has the same bug, and fix him too.

**Comment by Kubik161** [comment] 2020-01-16 19:50
This issue should be closed, Black File with Dr. Lovegood works correctly.

**Closed** 2020-01-16 20:13 UTC
Labels: bug, card, who-designed-this-game-anyway
