### ISSUE TITLE
runner approaches jagurundi, cannot proceed to encounter

### ISSUE THREAD

**Issue by yellowstonemagicstats** [mtgred/netrunner#6982] opened 2023-08-02 17:20 UTC
Link to bug replay: https://jinteki.net/bug-report/796416dc-00bd-4654-916e-555744e33249?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

**Comment by NBKelly** [comment] 2023-08-02 21:57
Duplicate of #6968.

It's fixed, but hasn't gone live yet.

**Comment by NBKelly** [comment] 2023-08-05 00:07
@NoahTheDuke this can be closed

**Closed** 2023-08-05 03:10 UTC
