### ISSUE TITLE
Exchange of information will activate On-steal effect on Sting!

### ISSUE THREAD

**Issue by gorka-larrea-montoya** [mtgred/netrunner#5923] opened 2021-05-31 18:52 UTC
Link to bug replay: https://jinteki.net/bug-report/fd3572fb-0ebf-44bd-899d-b449bc14e57c?b=0

Corp plays exchange of information, trading Sting! for Obokata protocol. Runner gets 1 net damage from the on-steal ability.
Note: Corp was playing Jinteki Personal Evolution, maybe that would activate too if i hadn't died from the sting first? Worth looking at too

**Comment by francescopellegrini** [comment] 2021-06-01 08:40
Duplicate of #5725?

**Comment by NoahTheDuke** [comment] 2021-06-01 14:23
Thanks for the report!

**Comment by francescopellegrini** [comment] 2022-07-23 20:37
Probably fixed by https://github.com/mtgred/netrunner/commit/5267e80a84ee55e7b2f33efa2b84c07d9785b853.

**Closed** 2022-07-23 21:46 UTC
Labels: bug, duplicate, card, engine
