### ISSUE TITLE
Stealth breakers keep strength

### ISSUE THREAD

**Issue by sirloathing1209** [mtgred/netrunner#5993] opened 2021-07-20 14:29 UTC
Penrose and Afterimage will maintain strength boost from stealth credits for the entire game. This has been true for awhile. I have noticed this when feeding them stealth credits from Mantle, Trickster Taka and Penumbral Toolkit.

**Comment by NoahTheDuke** [comment] 2021-07-20 14:36
Thanks for the report!

**Comment by francescopellegrini** [comment] 2021-07-23 06:53
Duplicate of #5935, will be fixed by #5942.

**Comment by francescopellegrini** [comment] 2021-07-27 18:45
Fixed by #5942

**Closed** 2021-07-27 18:49 UTC
Labels: bug, engine
