### ISSUE TITLE
EOI'ing tomorrow's headline incorrectly gives runner a tag

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5792] opened 2021-04-13 12:45 UTC
tolaasin spends  and pays 0  to play Exchange of Information.
tolaasin uses Exchange of Information to swap Tomorrow's Headline for Global Food Initiative.
tolaasin uses Tomorrow's Headline to give Runner 1 tag.

**Comment by NoahTheDuke** [comment] 2021-04-13 14:57
Thanks for the report!

**Comment by francescopellegrini** [comment] 2021-04-14 06:45
Duplicate of #5725

**Comment by francescopellegrini** [comment] 2022-07-23 20:33
Probably fixed by https://github.com/mtgred/netrunner/commit/5267e80a84ee55e7b2f33efa2b84c07d9785b853.

**Closed** 2022-07-23 21:46 UTC
Labels: bug, card, engine
