### ISSUE TITLE
Discarding Chairman Hiro after hosting an agenda on Film Critic

### ISSUE THREAD

**Issue by failtech** [mtgred/netrunner#1181] opened 2016-02-03 13:49 UTC
the corp player can´t discard chairman hiro without automatically putting it into the runners score pile.

**Comment by JoelCFC25** [comment] 2016-02-03 14:44
I am going to need more information on this--I've it reportedly intermittently and have **never** been able to reproduce it, despite trying every way I can think of.

**Comment by failtech** [comment] 2016-02-03 15:07
weird.
it happened every time i discarded because of hand limit when playing IG.
i will try to reproduce it myself will get back to you.

best regards,
hesy

**Comment by schnelge** [comment] 2016-02-15 20:07
Can confirm, when trashing Chairman Hiro from hand at the end of a turn (runner never accessed him), it automatically goes to the runner's score area, giving them 2 agenda points.

**Comment by zaroth** [comment] 2016-02-15 20:13
@schnelge could you copy a game log from that moment?

**Comment by schnelge** [comment] 2016-02-15 20:17
Do you mean from the chat window?

**Comment by zaroth** [comment] 2016-02-15 20:20
Yes, that would help with tracking down the exact situation this occurs.

**Comment by schnelge** [comment] 2016-02-15 20:24
Here you go:

(The browser window with the finished game is still open. Anything else I could dump in here?)

```
schnelge started their turn 15 with 7  and 5 cards in HQ.
schnelge spends  to draw a card.
schnelge spends  to install a card in New remote.
schnelge rezzes Jackson Howard.
schnelge spends  to use Jackson Howard to draw 2 cards.
schnelge trashes a card from their HQ.
schnelge trashes a card from their HQ.
schnelge trashes a card from their HQ.
schnelge is ending their turn 15 with 7  and 5 cards in HQ.

akashia
hmm
schnelge trashes a card.

akashia
why i got chairman

schnelge
i don't thnk that's correct ^_^
akashia wins the game.
akashia trashes a card.

schnelge
i guess because it was trashed
akashia started their turn 15 with 3 and 7 cards in their Grip.
akashia uses Beach Party to lose .
akashia uses Adjusted Chronotype to gain .

schnelge
but without being accessed...bug igeuess
akashia spends  and 3  to play Lucky Find.
akashia spends  to use Film Critic to add The Future Perfect to their score area and gain 3 agenda points.
akashia wins the game.
akashia wins the game.
akashia trashes a card.
akashia wins the game.
schnelge trashes a card.
akashia wins the game.
schnelge trashes a card.
akashia wins the game.
schnelge trashes a card.
akashia sets agenda point to 17 (-1).
akashia sets agenda point to 16 (-1).
akashia sets agenda point to 15 (-1).
akashia sets agenda point to 14 (-1).
akashia sets agenda point to 13 (-1).
akashia sets agenda point to 12 (-1).
akashia sets agenda point to 11 (-1).
akashia sets agenda point to 10 (-1).
akashia wins the game.
schnelge trashes a card.
akashia sets agenda point to 11 (-1).
akashia sets agenda point to 10 (-1).
akashia sets agenda point to 9 (-1).
akashia sets agenda point to 8 (-1).
akashia sets agenda point to 7 (-1).
akashia sets agenda point to 6 (-1).
akashia sets agenda point to 5 (-1).
akashia sets agenda point to 4 (-1).
akashia is ending their turn 15 with 9  and 6 cards in their Grip.
```

**Comment by JoelCFC25** [comment] 2016-02-15 20:24
I am more curious about what the Runner did on the turn preceding yours...

**Comment by zaroth** [comment] 2016-02-15 20:25
also, could you try using `/card-info` on the offending Haas?

**Comment by JoelCFC25** [comment] 2016-02-15 20:29
I poked my head in the remnant of the game...the bolded part is worth investigating for sure.

akashia started their turn 14 with 3 and 8 cards in their Grip.
akashia uses Beach Party to lose .
akashia uses Adjusted Chronotype to gain .
akashia spends  and 2  to install Hunting Grounds.
akashia makes a run on Server 6.
akashia uses Net-Ready Eyes to give Gingerbread +1 strength.
akashia uses Hunting Grounds to prevent a "when encountered" ability on a piece of ICE.
schnelge has no further action.
akashia continues the run.
schnelge has no further action.
***akashia uses Film Critic to host The Future Perfect instead of accessing it.***
akashia spends  to gain 1 .
akashia spends  to gain 1 .
akashia is ending their turn 14 with 3 and 7 cards in their Grip.

**Comment by schnelge** [comment] 2016-02-15 20:31
Runner's turn right before the turn I trashed Hiro:

```
akashia started their turn 14 with 3 and 8 cards in their Grip.
akashia uses Beach Party to lose .
akashia uses Adjusted Chronotype to gain .
akashia spends  and 2  to install Hunting Grounds.
akashia makes a run on Server 6.
akashia uses Net-Ready Eyes to give Gingerbread +1 strength.
akashia uses Hunting Grounds to prevent a "when encountered" ability on a piece of ICE.
schnelge has no further action.
akashia continues the run.
schnelge has no further action.
akashia uses Film Critic to host The Future Perfect instead of accessing it.
akashia spends  to gain 1 .
akashia spends  to gain 1 .
akashia is ending their turn 14 with 3  and 7 cards in their Grip.
```

/card-info on Hiro:


!schnelge uses a command: /card-info
schnelge shows card-info of a card in : {:faction "Jinteki", :limited 3, :agendapoints 2, :zone [:scored], :cid 394826, :type "Asset", :title "Chairman Hiro", :counter 0, :uniqueness true, :host nil, :code "05008", :side "Corp", :cost 2, :hosted nil, :advance-counter 0, :trash 6, :subtype "Executive", :previous-zone [:discard]}.

**Comment by zaroth** [comment] 2016-02-15 20:32
@schnelge Your report just saved some baby seals from Joel clubbing them! The issue is confirmed, it's a problem with Film Critic not closing `:access` phase properly.

**Comment by schnelge** [comment] 2016-02-15 20:33
Glad to hear, the world needs less baby seal clubbing! ^_^

**Closed** 2016-02-25 00:45 UTC
Labels: bug, cards
