### ISSUE TITLE
Option to host  on Flame-Out resets strength from Cybertrooper Talut

### ISSUE THREAD

**Issue by yojimbosteel** [mtgred/netrunner#4758] opened 2019-12-15 21:13 UTC
If after installing an Icebreaker you use Flame-Out to host, the strength of the Icebreaker will reset on the next click.

**Comment by mgsholte** [comment] 2020-11-02 18:58
Duplicate of #4770 

I know this ticket came first and the other is technically the duplicate, but the other ticket has more activity at this point.

**Comment by francescopellegrini** [comment] 2023-01-02 15:36
Might as well close this.

**Closed** 2023-01-02 16:15 UTC
