### ISSUE TITLE
Titanium Ribs bug

### ISSUE THREAD

**Issue by chrisferg** [mtgred/netrunner#2622] opened 2017-07-05 10:47 UTC
When Titanium Ribs is installed, most means of receiving brain damage (including stimhack and amped up, excluding brain cage) end up doing 2 brain damage instead of 1: you are prompted to choose the card to discard (because of titanium ribs), and it discards 1 random card as well. You then receive 2 brain damage instead of 1, and your max hand size is reduced by 2 instead of 1.

**Comment by JoelCFC25** [comment] 2017-07-05 12:46
Duplicate of #2466.

**Closed** 2017-07-10 13:35 UTC
Labels: bug, cards, duplicate
