### ISSUE TITLE
Maya & Equivocation

### ISSUE THREAD

**Issue by Macduffle** [mtgred/netrunner#2110] opened 2016-10-20 15:38 UTC
After using Equivocation, both using it's ability and not, Maya doesn't fire anymore.

**Comment by JoelCFC25** [comment] 2016-10-22 19:18
I haven't been able to reproduce this yet--in both the case of the Runner making the Corp draw and not, Maya is able to send the accessed card (original 2nd one down in the case of the forced draw, and top card if not) to the bottom.

**Comment by JoelCFC25** [comment] 2016-11-07 18:52
Any further occurrences?

**Comment by JoelCFC25** [comment] 2016-11-17 16:37
Closing due to lack of reproduction or feedback. If it occurs again, please respond and we'll reopen this.

**Closed by JoelCFC25** 2016-11-17 16:37 UTC
Labels: can't reproduce
