### ISSUE TITLE
Hayley + DJ Fenris

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4035] opened 2019-02-14 15:10 UTC
If installing DJ Fenris triggers Hayley, the list of IDs from DJ become part of the normal actions box and doesn't go away.  To duplicate:  Install DJ Fenris as Hayley with another resource in hand, when her ID had not yet triggered that turn.

![dj and hayley trigger glitch](https://user-images.githubusercontent.com/17117909/52795777-1e875c00-3038-11e9-98de-dae4238f8ecf.png)

**Comment by NoahTheDuke** [comment] 2019-02-14 15:12
Oh bummer, that sucks. Thanks for the report.

**Comment by Saintis** [comment] 2019-02-14 15:15
Duplicate of #3831, but does give clear reproduction instructions!

**Closed** 2020-05-21 19:16 UTC
Labels: bug, duplicate, game interface
