### ISSUE TITLE
Asa Group installing a card against 419 doesn't allow 419's ability to fire

### ISSUE THREAD

**Issue by profdeadpool** [mtgred/netrunner#3641] opened 2018-06-13 03:52 UTC
Yeah basically that.

I installed a ice, used Asa to install another ice from hand, and the 419 player was never given a chance to expose that ice.

**Comment by Saintis** [comment] 2018-07-03 10:36
Duplicate of #3590

**Closed by Saintis** 2018-07-03 10:36 UTC
