### ISSUE TITLE
Usernames hover/highlight issues

### ISSUE THREAD

**Issue by squogfloogle** [mtgred/netrunner#2101] opened 2016-10-18 08:18 UTC
Seems that this was reported with issue #429, but "1" from there either wasn't fixed or has recurred with a later update.

Highlighting a username that is also a card name brings up the preview for that card. See screenshot below! Guessing we need to ignore card highlights on usernames?

![bug](https://cloud.githubusercontent.com/assets/12003596/19469549/4c726162-9578-11e6-8abb-132fe642e99c.PNG)

**Comment by JoelCFC25** [comment] 2016-10-18 09:32
Thanks, but this is a duplicate of #1725. Discussion will continue there if this is ever deemed fixable.

**Closed by JoelCFC25** 2016-10-18 09:32 UTC
Labels: duplicate, game interface

**Comment by squogfloogle** [comment] 2016-10-18 09:34
Aha, sorry about that. Tried a search but didn't find that one. Thanks for all your work!
