### ISSUE TITLE
Film Critic multiplies agendas

### ISSUE THREAD

**Issue by gandrasch** [mtgred/netrunner#573] opened 2015-08-21 13:28 UTC
So now that we can host agendas on Film Critic a problem occured to me. After hosting the agenda on FM, I paid two clicks to get the agenda into my score area. It appeared there correctly but also was still on my Film Critic. And I could add it endless times to my score area (still paying the two clicks though). 

Only resolution was to trash and reinstall Film Critic, but that adds a second copy of the agenda to the discard pile of the corp.

**Comment by queueseven** [comment] 2015-08-21 14:20
Well, that's sounds a little bit overpowered....

**Comment by queueseven** [comment] 2015-08-21 14:24
I tested this and can't reproduce it. Can you give some more information what you did exactly? Can you reproduce it yourself?

**Comment by nealterrell** [comment] 2015-08-21 15:10
Yes, knowing the IDs and agenda in question would be very helpful :).

**Comment by gandrasch** [comment] 2015-08-21 16:00
Film Critic was hosted in off Campus.

Am Freitag, 21. August 2015 schrieb Dominic Kexel :

**Comment by nealterrell** [comment] 2015-08-21 16:03
OFF CAMPUS APARTMENT, ugh. Definitely related to that, since we also have reports of resources duplicating when removed from The Supplier hosted on Off Campus.

**Comment by nealterrell** [comment] 2015-08-31 01:47
I submitted a fix for this in #648.

**Closed** 2015-08-31 22:59 UTC
Labels: bug
