### ISSUE TITLE
Jinja City Grid did not give a prompt when drawing an ice with a regular click action

### ISSUE THREAD

**Issue by CasMat9** [mtgred/netrunner#3769] opened 2018-07-16 17:13 UTC
The ice was Data Raven. The only other ability used on that turn was to rez and gain credits from NGO Front. Jinja later gave prompts in the match normally, though I did not have the opportunity to draw another ice with the regular click action.

**Comment by nealterrell** [comment] 2018-07-17 15:08
I can't reproduce this, and I'm sure we would've received many reports if click-draw was broken with Jinja. Let me know if you see it agian.

**Comment by CasMat9** [comment] 2018-07-19 00:52
Took a screenshot and copied log.
![jinjabugscreen](https://user-images.githubusercontent.com/4683711/42915203-65c7e9de-8acc-11e8-88ec-0a2603e81535.png)
[JinjaBugLog.docx](https://github.com/mtgred/netrunner/files/2207782/JinjaBugLog.docx)

**Comment by nealterrell** [comment] 2018-07-19 00:54
Thank you for the effort to recreate this. I'll see what I can find out.

**Comment by ZomBagus** [comment] 2018-07-20 17:42
![image](https://user-images.githubusercontent.com/13881796/43016932-635bf948-8c4c-11e8-99a6-ba5a6456ddb5.png)

**Comment by ZomBagus** [comment] 2018-07-20 20:48
![image](https://user-images.githubusercontent.com/13881796/43024495-6c141fec-8c66-11e8-85a7-94beeff0677a.png)

**Comment by ZomBagus** [comment] 2018-07-20 20:49
UVC 3 ice, no jinja trigger

**Comment by hiddenaway1** [comment] 2018-07-25 17:30
I can't reproduce the UVC error, though I have had it before. The draw error is completely random though. Sometimes it works and sometimes it doesn't (this is based on solo corp testing, giving myself loads of clicks and constantly drawing with a Jinja rezzed).

I'll try and record something tomorrow to see if there are any patterns.

**Comment by NoahTheDuke** [comment] 2018-07-26 00:31
You're a champion. This'll be extremely helpful, thank you.

**Comment by hiddenaway1** [comment] 2018-07-26 19:01
Right, I believe I can see some patterns in the behavior now. I've added more tests here (all solo):

https://drive.google.com/open?id=1W85ZBKTt6-OHHeJnh6i5OKNqcJ2DsK-d

1. With Jinja installed, if you draw an ICE and it doesn't trigger, and then you draw another ICE then Jinja will trigger correctly (but only on your newly drawn ICE).

2. If you draw a non-ICE card and then instantly draw an ICE, it's almost certain that Jinja DOES NOT work. This also tends to happen if you draw a Jinja, install and rez and then draw into an ICE (at least a few times I tried). It doesn't always happen though (sometimes I would see non-ICE cards for about 4-5 clicks and then Jinja triggers on the next ICE). This also applies when you hit UVC or other draw abilities.

3. UVC can fire correctly IF you drew an ICE previously. It's a bit hard to see because these tests are done with effectively infinite clicks. It won't always trigger even if you draw 4 ICE in one go though (see 2).

4. The last 2 tests were of me messing around with the card order to try and get Jinja to trigger. For example, you can see me adding ICE to the top of R&D to guarantee a Jinja trigger.

I hope all this is useful to you all. Hoping to try out a couple of proper games later to really figure everything out. I'd love to try and fix it myself but looking at the code, I don't think the fix will be that easy for me to figure out with my limited knowledge :)

**Comment by nealterrell** [comment] 2018-07-26 21:06
OK, so with those notes my current thought is that Jinja is not receiving `:post-corp-draw` in some scenarios. The card uses a slight hack in that it is marked `:once :per-turn`, even though it's not actually "once per turn" ... this is done so that multiple Jinjas can collaborate on a single install sequence, instead of each Jinja triggering independently. The `:once` key makes it so only one Jinja gets to react to `:corp-draw`, and then we do a hack in `:post-corp-draw` to clear that key so Jinja can respond again the next draw.

If `:post-corp-draw` were broken in some way, then Jinja would never clear its once-key and would ignore the next `:corp-draw` event. This seems to fit some of your experiences, where the card will work the NEXT draw after one that it misses. It sounds to me like the PREVIOUS draw did not trigger `:post-corp-draw` correctly, so Jinja did not clear itself and thus did not respond to the next draw event... but that draw event presumably did trigger `:post-corp-draw` correctly, setting Jinja up to respond to the NEXT draw correctly.

Now why would this be happening? Not sure. Either someone messed up the core draw routines (it doesn't look like anyone has touched them recently) or maybe Jinja's `:corp-draw` event isn't fully resolving somehow, so the code in the core engine that waits for `:corp-draw` to finish before triggering `:post-corp-draw` is hanging. I'll investigate.

**Comment by nealterrell** [comment] 2018-07-28 00:00
Thanks gang, we got it.

**Closed** 2018-07-28 03:44 UTC
Labels: bug
