### ISSUE TITLE
Setting up Filters in Card Viewer

### ISSUE THREAD

**Issue by Arkinod** [mtgred/netrunner#2593] opened 2017-06-12 14:53 UTC
When trying to select options from any drop down in the card view filter section, the drop down does not stay open long enough to actually scroll through the list and select an option.  It acts as if the box suddenly forgets the cursor is actually interacting with it and closes of its own accord.  I am accessing the site through Chrome Version 58.0.3029.110 (64-bit), on a Windows 7 PC.

**Comment by JoelCFC25** [comment] 2017-06-12 14:57
Duplicate of #2427, track any future progress in that issue.

**Closed by JoelCFC25** 2017-06-12 14:57 UTC
Labels: duplicate, site interface
