### ISSUE TITLE
Ruhr Valley Running

### ISSUE THREAD

**Issue by Matt500** [mtgred/netrunner#2614] opened 2017-06-24 07:36 UTC
Hi there, found a potential issue with Ruhr Valley just wanted to run by.

Corp had an installed and rezzed Ruhr Valley on a remote with one ice protecting.

Click 1 i ran and was fine. however on next click to run again, the option was not able to be selected.

I thought because Enhance Login Protocol's was up it might be a problem but with 3 clicks, i had 1 spare so therefore i thought i could run.

i have attached a screenshot. nothing else was preventing me (no card abilities etc)

next turn i tried to same ol thing inside job on click 1 and 2, but could not run Ruhr Valley server as it was not able to be selected.

<img width="523" alt="potential ruhr valley bug" src="https://user-images.githubusercontent.com/29672108/27506754-4e197768-5903-11e7-8c76-f05b1dd94dfc.PNG">

if you can't see the pic let me know i'll email instead.

Cheers, keep up the great work

Matt500

**Comment by JoelCFC25** [comment] 2017-06-24 12:24
Thanks. This is a duplicate of #2109.

**Comment by danhut** [comment] 2018-04-02 00:45
Closing as it is a duplicate

**Closed by danhut** 2018-04-02 00:45 UTC
Labels: bug, cards, duplicate
