### ISSUE TITLE
Enhancement: Delete Multiple/All Decklists

### ISSUE THREAD

**Issue by NoahTheDuke** [mtgred/netrunner#3664] opened 2018-06-24 13:20 UTC
It can be very cumbersome to delete decks one at a time, especially when you have a lot of them. Allow selecting multiple or all of the decks and performing actions on them.

**Comment by JoelCFC25** [comment] 2018-06-24 13:47
Actually a duplicate of #2287.

**Comment by NoahTheDuke** [comment] 2018-06-24 13:51
Whoops, thanks.

**Comment by queueseven** [comment] 2018-07-18 09:51
closed because duplicate of #2287.

**Closed** 2018-07-18 09:50 UTC
