### ISSUE TITLE
Provide a cancel option when triggering simulchip

### ISSUE THREAD

**Issue by AlexBoyd** [mtgred/netrunner#5724] opened 2021-03-30 20:10 UTC
There are occasions where as a runner you trigger simulchip, only to discover you are short mu, credits, forgot that you hadn't already trashed a program, or just that the target you are looking for isn't in the bin. In that case you often want to abort using simulchip after you are already part way through using it.  

IE at this step: 

![image](https://user-images.githubusercontent.com/841094/113049235-3fe42d00-9158-11eb-8c5b-f109ec46c864.png)

Currently the cleanest way to do that is to use /close-prompt, give yourself a credit and a click, drag simulchip to hand and then reinstall it. That can be very awkward though as you might be mid run, on the corps turn etc. This could be a problem if jnet also starts to enforce preventing the runner from randomly grabbing / using clicks in windows they shouldn't be able to do so. It also gets messy if they are things with on install / on trash triggers like tech traders / geist / hayley, or tech writer. 

A nice UX improvement would be to add a cancel option during the simulchip prompt, and that the chip itself gets trashed only after selecting a target. 

This could be similar to the cancel prompt on other triggers such as Wu, that shows up as an option in the space where the UI is prompting the simulchip targeting. 
![image](https://user-images.githubusercontent.com/841094/113050052-4626d900-9159-11eb-9782-8cedcdaf3728.png)

**Comment by NoahTheDuke** [comment] 2021-03-31 03:32
Thanks for the suggestion!

**Comment by NBKelly** [comment] 2024-09-19 07:47
Costs are not cancellable by design, and we can't have you pre-select the program to install because then you couldn't flicker stuff. It's slightly inconvenient, but I don't think there's a way around this at all for simulchip.

Maybe once I figure out paid ability windows, we'll just be able to rewing the PAW.

For now, I'm closing this issue as not planned.

**Closed by NBKelly** 2024-09-19 07:47 UTC
Labels: enhancement, card
