### ISSUE TITLE
Crisium Grid effect lasting through subsequent runs, even after trashing

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#941] opened 2015-12-01 18:55 UTC
Crisium Grid, if activated once, seems to assume that no further runs on that server for the entire turn are successful, even if it is trashed and a subsequent successful run is made on the server.

An example from an actual game. Playing Chaos Theory, have removed a Hyperdriver from the game, have three Notoriety in hand that I plan to play with my last 3 clicks.

* Click 1: Run HQ with Legwork. Break the ice. Facedown upgrade is rezzed, it's Crisium Grid, Legwork fizzles but I access 1 card from hand normally. I then access and trash the Crisium.
* Click 2: Run HQ normally. Break the ice. Access 1 card from hand.
* Click 3: Run R&D with Maker's Eye. Break the ice. See three cards from R&D.
* Click 4: Run Archives. See nothing of consequence.
* Click 5: Try to play Notoriety. It cannot be played from hand, presumably because the Crisium run on HQ has created a game state where my subsequent successful run on HQ didn't count.

**Comment by JoelCFC25** [comment] 2015-12-01 22:12
Interesting. I can't reproduce this in dev yet--replicating this scenario exactly, I checked `[:runner :register]` in the game state immediately after click 4 and saw that it had a record of successful runs on HQ, R&D, and Archives. I was then able to play Notoriety. 

Not to sound like one of those tech support "Is your computer plugged in?" questions, but....you had 1 credit on hand to play the Notoriety with, right? :)

**Comment by stoppableforce** [comment] 2015-12-01 22:23
Yup - I had somewhere between 17 and 23 credits (I don't remember the exact count but my credits fluctuated there for the rest of the game, all 1 turn of it).

**Comment by JoelCFC25** [comment] 2015-12-02 02:58
I tried it on live just now and was also able to play Notoriety successfully...mystifying!

**Comment by JoelCFC25** [comment] 2015-12-09 07:39
@stoppableforce: Can you reliably reproduce this yet? I will try again now that there has been a server reset.

**Comment by JoelCFC25** [comment] 2015-12-15 14:14
I'm going to close this for now. If it flares up again and becomes widely reported we can revisit it.

**Comment by adam-higuera** [comment] 2015-12-29 23:08
Just chiming in to say that I also observed this, also with Notoriety and Chaos Theory.

Since you are having difficulty reproducing the issue, I'll provide more info: I accessed and trashed the Crisium grid in the same turn that I tried to play Notoriety, I had run both other central servers earlier in the turn, I had run Archives normally, I had run HQ with both Vamp (so, a replacement effect) and Legwork (a non-replacement effect).  Both runs on R&D were normal runs.  The Crisium Grid was the _second_, chronologically, upgrade installed in the root of R&D.

**Comment by JoelCFC25** [comment] 2015-12-30 01:20
A-ha! Thanks for prompting me to revisit this--I discovered the issue (and why I hadn't seen it). Crisium Grid is snipping off the wrong item from the list stored in `[:runner :register]` of servers that have been successfully run during the turn. Using the exact scenario you laid out, if I successfully run (by click or event, doesn't matter) in the following order: Archives, HQ, HQ...

...what goes into `[:runner :register :successful-run]` is: `(:hq :hq :archives)`  (i.e., the most recent one is being added onto the front of the list). However, Crisium Grid's code is using `butlast` to replace this list with everything but the last item--so if I now run R&D with the rezzed Grid, the same list now reads: (:rd :hq :hq)...it's wrongly chopped off the good run on Archives. 

When I was testing this before I was always running the server with the Crisium Grid first, trashing it, then running that server again right away--so the server being removed coincidentally happened to be right.

**Closed** 2015-12-31 06:13 UTC
Labels: bug
