### ISSUE TITLE
Chat box reports lots of code when preventing damage with Feedback Filter

### ISSUE THREAD

**Issue by emilyfrog** [mtgred/netrunner#1417] opened 2016-04-02 23:35 UTC
Not sure if it's helpful to post this here; I assume it's similar to the Plascrete Carapace bug submitted earlier.  

EDIT: should have said - it was when preventing damage caused by the new card Bio-Ethics Association and yes, I should have trashed it sooner...

**Comment by JoelCFC25** [comment] 2016-04-03 02:09
Thanks for the report. This does turn out to be a duplicate of #1415. I'm submitting the fix shortly!

**Closed** 2016-04-04 06:36 UTC
Labels: bug, duplicate
