### ISSUE TITLE
Magnet not removing abilities on Chisel

### ISSUE THREAD

**Issue by ALiteralCommunist** [mtgred/netrunner#6549] opened 2022-08-18 01:53 UTC
I don't know if this happens with other cards, but when I used Magnet to move a Chisel from another piece of ice, the Chisel still reduced Magnet's strength. 
![image](https://user-images.githubusercontent.com/82968748/185274895-6e0976b7-a4ae-489c-94e3-ad99a890c114.png)

**Comment by francescopellegrini** [comment] 2022-08-18 06:27
Duplicate of #5790

**Closed** 2022-09-15 12:49 UTC
Labels: duplicate
