### ISSUE TITLE
Hanging prompt for corp on runner's turn with Beth installed and corp at < 5 credits

### ISSUE THREAD

**Issue by AlexBoyd** [mtgred/netrunner#4177] opened 2019-04-02 04:49 UTC
I've recently spotted what appears to be a consistently reproducible issue with Beth. 

When starting my turn as a runner with Beth installed, and the corp below 5 credits the following happens.
1. Rather than starting the turn directly and granting clicks, it transitions to a "take clicks" action even though there should be no start of turn effects that need to be manually sequenced. 
2. The start of turn messages in the chat, is posted twice, once when clicking "start turn" and again when clicking take clicks. 
3. Sometimes when Rezeki's are installed, they fire twice, once on start of turn and once when taking clicks. This seems inconsistent, and might be based on some non deterministic trigger order. 
4. A hanging prompt of some sort is left up for the corp that persists until they do a manual "/close-prompt" action. 

This will happen consistently until the corp gets back up above 5 credits, at which points things return to normal, so I'm fairly certain it's a bug with the Beth start turn trigger not cleaning up properly after itself when none of the 3 cases where it's granted a benefit has fired.

**Comment by NoahTheDuke** [comment] 2019-04-02 10:51
Thanks for the detailed report! This is a duplicate of #4177

**Closed** 2019-04-11 01:24 UTC
Labels: bug, cards, duplicate
