### ISSUE TITLE
Snare! doesn't wait for the corp to resolve before the runner can continue acting

### ISSUE THREAD

**Issue by thehunter518** [mtgred/netrunner#576] opened 2015-08-21 19:57 UTC
This is certainly not a game-breaking issue, especially for patient and polite players, but the corp's prompt upon the runner accessing Snare! (Pay 4 credits to deal 3 net damage and force the runner to take one tag?) doesn't actually wait for the corp's response - the runner can continue taking actions while you are deciding what to do. For example, if you have a Snare! on a remote server and a Dedicated Response Team rezzed, the runner can trash the Snare!, complete their run, and end their turn all before you've decided whether or not you'd like to fire it (this actually directly interferes with Dedicated Response Team working properly).

If this is happening on Snare, it's probably happening on other traps as well (although I'm pretty sure that Psi games DO correctly make the runner wait until you've revolved them).

**Comment by JoelCFC25** [comment] 2015-08-21 20:05
Yep, this is broadly problematic for lots of card interactions. See the duplicate of this at #423, but also #445, #309, and even #189 (sort of).

**Comment by nealterrell** [comment] 2015-12-30 19:38
Fix submitted in #1059.

**Closed** 2016-01-07 17:00 UTC
Labels: dev, duplicate, enhancement
