### ISSUE TITLE
Chairman Hiro Problem

### ISSUE THREAD

**Issue by sluissanchez** [mtgred/netrunner#398] opened 2015-07-18 22:45 UTC
When the corp trashes from grip chairman hiro to Archives, if the corp moves chairman Hiro from archives and trashes chairman hiro, then chairman hiro moves to runner's punctuation area, counting two agenda points.

**Comment by JoelCFC25** [comment] 2015-07-20 14:22
I can't reproduce this bug. I tried a deck that had Chairman Hiro, Director Haas, and The Board (if Chairman Hiro was doing this, they all should). As Corp I tried trashing from hand, trashing from a remote to replace with something else, and everything you described.

**Comment by sluissanchez** [comment] 2015-07-20 15:58
The problem occurs when I get Chairman Hiro from Archives, and move it to Archives. It's a problem made by the user. I Know, but I get this situation in two games played last weekend.

**Comment by sluissanchez** [comment] 2015-07-20 15:58
Sorry, I push the incorrect button...

**Comment by JoelCFC25** [comment] 2015-07-20 16:20
I still can't reproduce it--tried grabbing Chairman Hiro from Archives, putting it in HQ, and moving it back to Archives. Also tried pulling it out of Archives and immediately dropping it back in.

**Comment by JoelCFC25** [comment] 2015-08-12 15:54
Closing this due to no further reports. If it happens again and you can reproduce it, add another comment and we'll reopen it.

**Closed by JoelCFC25** 2015-08-12 15:54 UTC
Labels: can't reproduce
