### ISSUE TITLE
Playing currents in sol consistently triggers erros

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2154] opened 2016-11-10 20:22 UTC
Please describe the circumstances of your error here.

Stack Trace:
```clojure
Error do choice Hyperdriver #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.string$lower_case invokeStatic "string.clj" 217]}]
 :trace
 [[clojure.string$lower_case invokeStatic "string.clj" 217]
  [clojure.string$lower_case invoke "string.clj" 213]
  [game.core$resolve_prompt$fn__4447 invoke "actions.clj" 129]
  [clojure.core$some invokeStatic "core.clj" 2592]
  [clojure.core$some invoke "core.clj" 2583]
  [game.core$resolve_prompt invokeStatic "actions.clj" 129]
  [game.core$resolve_prompt invoke "actions.clj" 113]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 150]
  [game.main$handle_command invoke "main.clj" 139]
  [game.main$run$fn__25520 invoke "main.clj" 185]
  [game.main$run invokeStatic "main.clj" 175]
  [game.main$run invoke "main.clj" 169]
  [game.main$_main$fn__25555 invoke "main.clj" 239]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by tolaasin** [comment] 2016-11-10 20:23
Targeted marketing consistently gives game errors at the moment.

**Comment by JoelCFC25** [comment] 2016-11-10 20:35
Thanks--duplicate of #2152, #2148, #2146.

**Comment by nealterrell** [comment] 2016-11-10 22:56
Is this just with Targeted Marketing? (Implied otherwise in title.)

**Comment by tolaasin** [comment] 2016-11-11 10:45
Yes, it's just with tarmar. Scarcity worked fine.

**Closed** 2016-11-15 14:15 UTC
Labels: bug, duplicate
