### ISSUE TITLE
MirrorMorph prompt happening too soon.

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#6035] opened 2021-08-30 18:54 UTC
MMs ability triggers when the third action COMPLETES. It currently triggers when it's INITIATED. Usually doesn't wholly matter but when drawing or playing a draw spell on the 3rd action, you don't see the cards before deciding what to use MM for, which isn't how it should behave.

Example is drawing with the 3rd unique action:

Expected behavior:

Drawing with 3rd action, you have the card in hand, then decide on the mirrormorph trigger.

What is happening:

MM is interrupting the draw, giving you the prompt and halting the draw resolution until the choice is made.

Repo rate:

100%

**Comment by francescopellegrini** [comment] 2021-12-27 19:16
Duplicate of #5809

**Comment by francescopellegrini** [comment] 2023-01-02 15:36
Might as well close this.

**Closed** 2023-01-02 16:15 UTC
