### ISSUE TITLE
Trashing with Titanium Ribs

### ISSUE THREAD

**Issue by Greasythumb** [mtgred/netrunner#2460] opened 2017-03-30 21:06 UTC
I feel kind of guilty for wasting your time with such extraordinary jank, but...

Trashing for brain damage with titanium ribs (with cards like amped up, stimhack and Stim dealer) appears to double up the damage rather than simply reassigning it. You trash a card with titanium ribs, then you take the same damage again. Not ideal. Possibly this will become more relevant if Clan Vengeance becomes a thing. Probably not.

**Comment by JoelCFC25** [comment] 2017-03-30 23:09
Duplicate of #2459, fixed already in #2455. That fix will not be active on live server until after the next restart.

**Closed by JoelCFC25** 2017-03-30 23:09 UTC
Labels: bug, cards, duplicate
