### ISSUE TITLE
Levy AR Acess Lab does not resolve fully

### ISSUE THREAD

**Issue by Synisill** [mtgred/netrunner#4161] opened 2019-03-27 17:48 UTC
Today i played again after my holidays - and found out that Levy's does not draw 5 cards after reshuffling. Played another game to verify - it's broken right now.

**Comment by NoahTheDuke** [comment] 2019-03-27 18:06
Duplicate of #4089. Leaving this one open so others can find it.

**Closed** 2019-03-28 14:51 UTC
Labels: bug, cards, duplicate
