### ISSUE TITLE
News Hound triggers a psi game when a current is played

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4452] opened 2019-08-23 14:02 UTC
wu v Palana with cerebral static. Whenever News hound  is rezzed or a current played/lost eg on stealing, a psi game was triggered.

**Comment by NoahTheDuke** [comment] 2019-09-26 20:44
I can't reproduce this. Do you have any other information or steps to reproduce?

**Comment by tolaasin** [comment] 2019-09-27 08:07
Alas, no - was a single instance in a game.

**Comment by francescopellegrini** [comment] 2023-01-02 15:31
Might as well close this.

**Closed** 2023-01-02 16:16 UTC
Labels: bug, card
