### ISSUE TITLE
Close-prompt issue everytime a player ends their turn and passed the turn over

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#3623] opened 2018-06-09 03:58 UTC
The close prompt is required because waiting for corp to finish their action window keeps prompting.

**Comment by vkl125** [comment] 2018-06-09 04:04
vincentkbl
vincentkbl
hi
vincentkbl takes a mulligan.
0-Coast
0-Coast
hi glhf
0-Coast keeps their hand.
vincentkbl started their turn 1 with 5  and 5 cards in HQ.
vincentkbl spends  to install a card in Server 1 (new remote).
vincentkbl spends  to install a card in Server 2 (new remote).
vincentkbl spends  to install ICE protecting R&D.
vincentkbl is ending their turn 1 with 5  and 3 cards in HQ.
0-Coast started their turn 1 with 5 and 5 cards in their Grip.
0-Coast spends  to draw a card.
0-Coast spends  to draw a card.
0-Coast spends  and 1  to install Cache.
0-Coast uses Hayley Kaplan: Universal Scholar to install Paricia.
0-Coast installs Paricia.
0-Coast uses Cache to gain 1 .
0-Coast uses Cache to gain 1 .
0-Coast uses Cache to gain 1 .
0-Coast spends  and 1  to install Aesop's Pawnshop.
0-Coast is ending their turn 1 with 6  and 4 cards in their Grip.
vincentkbl rezzes Mental Health Clinic.
vincentkbl spends 2  to rez Marilyn Campaign.
vincentkbl started their turn 2 with 3  and 3 cards in HQ.
vincentkbl uses Marilyn Campaign to gain 2 .
vincentkbl uses Mental Health Clinic to gain 1 .
vincentkbl spends  to draw a card.
vincentkbl spends  to draw a card.
vincentkbl spends  to install a card in Server 3 (new remote).
vincentkbl is ending their turn 2 with 6  and 5 cards in HQ.
0-Coast started their turn 2 with 6 and 4 cards in their Grip.
0-Coast uses Aesop's Pawnshop to trash Cache and gain 3 .
0-Coast spends  to make a run on Server 2.
vincentkbl uses Mti Mwekundu: Life Improved to install ice at the innermost position of this server. Runner is now approaching that ice.
vincentkbl installs ICE protecting [:remote2].
0-Coast
0-Coast
let's see how this works
vincentkbl spends 2  to rez Sadaka.
0-Coast
0-Coast
ok
vincentkbl rearranges the top 3 cards of R&D.
vincentkbl uses Sadaka to draw 1 card.
vincentkbl trashes a card from HQ.
vincentkbl uses Sadaka to trash Aesop's Pawnshop.
vincentkbl trashes Sadaka.
vincentkbl has no further action.
vincentkbl continues the run.
vincentkbl has no further action.
0-Coast accesses Mental Health Clinic from Server 2.
0-Coast uses Paricia to take 1 .
0-Coast uses Paricia to take 1 .
0-Coast pays 3 to trash Mental Health Clinic from Server 2.
0-Coast spends  to draw a card.
0-Coast spends  to draw a card.
0-Coast spends  and 2  to install Beth Kilrain-Chang.
0-Coast uses Hayley Kaplan: Universal Scholar to install Same Old Thing.
0-Coast installs Same Old Thing.
0-Coast is ending their turn 2 with 6  and 4 cards in their Grip.
vincentkbl started their turn 3 with 4  and 4 cards in HQ.
vincentkbl uses Marilyn Campaign to gain 2 .
vincentkbl spends  to gain 1 .
vincentkbl spends  to gain 1 .
vincentkbl spends  to install ICE protecting Server 4 (new remote).
vincentkbl is ending their turn 3 with 8  and 4 cards in HQ.
vincentkbl spends 2  to rez Turtlebacks.
vincentkbl sets credit to 7 (+1).
vincentkbl derezzes Turtlebacks.
vincentkbl sets credit to 8 (+1).
vincentkbl
vincentkbl
oops
0-Coast
0-Coast
np
0-Coast started their turn 3 with 6 and 4 cards in their Grip.
0-Coast uses Beth Kilrain-Chang to gain 1 .
0-Coast spends  to draw a card.
0-Coast spends  to draw a card.
0-Coast spends  to draw a card.
0-Coast spends  to install Harbinger.
0-Coast uses Hayley Kaplan: Universal Scholar to install Harbinger.
0-Coast installs Harbinger.
0-Coast is ending their turn 3 with 7  and 5 cards in their Grip.
vincentkbl started their turn 4 with 8  and 4 cards in HQ.
vincentkbl uses Marilyn Campaign to gain 2 .
vincentkbl spends  to install a card in Server 4.
vincentkbl spends 2  to rez Turtlebacks.
vincentkbl uses Turtlebacks to gain 1 .
vincentkbl spends  to install a card in Server 5 (new remote).
vincentkbl spends  to gain 1 .
vincentkbl is ending their turn 4 with 10  and 3 cards in HQ.
0-Coast started their turn 4 with 7 and 5 cards in their Grip.
0-Coast uses Beth Kilrain-Chang to draw 1 card.
0-Coast spends  to make a run on HQ.
vincentkbl has no further action.
0-Coast accesses Crick from HQ.
0-Coast spends  to draw a card.
0-Coast spends  to install Self-modifying Code.
0-Coast uses Hayley Kaplan: Universal Scholar to install Misdirection.
0-Coast installs Misdirection.
0-Coast spends  and 1  to install Aesop's Pawnshop.
0-Coast is ending their turn 4 with 6  and 4 cards in their Grip.
vincentkbl spends 1  to rez Jinja City Grid.
vincentkbl started their turn 5 with 9  and 3 cards in HQ.
vincentkbl uses Marilyn Campaign to gain 2 .
vincentkbl uses Marilyn Campaign to shuffle it back into R&D.
vincentkbl uses Turtlebacks to gain 1 .
vincentkbl spends  to install a card in Server 6 (new remote).
vincentkbl spends  to draw a card.
vincentkbl uses Turtlebacks to gain 1 .
vincentkbl spends  to install a card in Server 7 (new remote).
vincentkbl is ending their turn 5 with 13  and 3 cards in HQ.
0-Coast started their turn 5 with 6 and 4 cards in their Grip.
0-Coast uses Beth Kilrain-Chang to draw 1 card.
0-Coast uses Aesop's Pawnshop to trash Harbinger and gain 3 .
0-Coast installs a card facedown.
0-Coast spends  to draw a card.
0-Coast spends  to make a run on HQ.
vincentkbl has no further action.
0-Coast accesses Crick from HQ.
0-Coast spends  to make a run on Server 7.
vincentkbl uses Mti Mwekundu: Life Improved to install ice at the innermost position of this server. Runner is now approaching that ice.
vincentkbl installs ICE protecting [:remote7].
vincentkbl spends 8  to rez DNA Tracker.
0-Coast spends 2  to use Self-modifying Code to install Cyber-Cypher.
0-Coast spends 2  to install Cyber-Cypher.
0-Coast uses Cyber-Cypher to target Server 7.
0-Coast spends 2  to increase the strength of Cyber-Cypher to 6.
0-Coast spends 1  to use Cyber-Cypher to break 1 Code Gate subroutine.
0-Coast spends 1  to use Cyber-Cypher to break 1 Code Gate subroutine.
0-Coast spends 1  to use Cyber-Cypher to break 1 Code Gate subroutine.
vincentkbl has no further action.
0-Coast continues the run.
vincentkbl has no further action.
0-Coast accesses Daily Business Show from Server 7.
0-Coast spends  to gain 1 .
0-Coast discards Paperclip from their Grip.
0-Coast is ending their turn 5 with 1  and 5 cards in their Grip.
vincentkbl spends 2  to rez Marilyn Campaign.
vincentkbl spends 2  to rez Daily Business Show.
vincentkbl started their turn 6 with 1  and 2 cards in HQ.
vincentkbl uses Marilyn Campaign to gain 2 .
vincentkbl uses Daily Business Show to draw additional cards.
vincentkbl reveals that they drew Anansi.
vincentkbl installs ICE protecting Server 4.
vincentkbl uses Daily Business Show to add 1 card to the bottom of R&D.
vincentkbl spends  to gain 1 .
vincentkbl spends  to gain 1 .
vincentkbl spends  to gain 1 .
vincentkbl is ending their turn 6 with 6  and 2 cards in HQ.
vincentkbl
vincentkbl
close-prompt issue?
!0-Coast uses a command: /close-prompt
0-Coast started their turn 6 with 1 and 5 cards in their Grip.

!0-Coast uses a command: /close-prompt
0-Coast started their turn 7 with 7 and 5 cards in their Grip.
close prompt issue
!0-Coast uses a command: /close-prompt

!0-Coast uses a command: /close-prompt

!0-Coast uses a command: /close-prompt

!0-Coast uses a command: /close-prompt

!0-Coast uses a command: /close-prompt
!0-Coast uses a command: /close-prompt
vincentkbl spends  to install ICE protecting Server 13.
vincentkbl is ending their turn 12 with 10  and 2 cards in HQ.
0-Coast started their turn 12 with 15  and 5 cards in their Grip.
0-Coast uses Beth Kilrain-Chang to draw 1 card.
0-Coast uses Aesop's Pawnshop to trash Harbinger and gain 3 .
0-Coast installs a card facedown.
0-Coast spends  to make a run on Server 14.
vincentkbl has no further action.
vincentkbl wants to act before the run is successful.
0-Coast accesses Corporate Town from Server 14.
vincentkbl
vincentkbl
dang
0-Coast uses Paricia to take 1 .
0-Coast uses Paricia to take 1 .
0-Coast pays 5 to trash Corporate Town from Server 14.
vincentkbl uses Hostile Infrastructure to do 1 net damage.
0-Coast trashes Gordian Blade due to net damage.
vincentkbl
vincentkbl
i keep clicking the wrong button
vincentkbl
vincentkbl
meant to click corp id
0-Coast
0-Coast
how about
0-Coast spends  to make a run on Server 16.
0-Coast
0-Coast
now
vincentkbl uses Mti Mwekundu: Life Improved to install ice at the innermost position of this server. Runner is now approaching that ice.
vincentkbl installs ICE protecting [:remote16].
vincentkbl spends 8  to rez DNA Tracker.
0-Coast spends 2  to use Self-modifying Code to install Nyashia.
0-Coast spends 2  to install Nyashia.
0-Coast indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
0-Coast indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
0-Coast indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
vincentkbl uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
0-Coast trashes Astrolabe due to net damage.
vincentkbl uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
0-Coast trashes Cerberus "Lady" H1 due to net damage.
vincentkbl uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
0-Coast trashes Cyber-Cypher due to net damage.
vincentkbl has no further action.
0-Coast continues the run.
vincentkbl has no further action.
0-Coast accesses Jeeves Model Bioroids from Server 16.
0-Coast pays 5 to trash Jeeves Model Bioroids from Server 16.
vincentkbl uses Hostile Infrastructure to do 1 net damage.
0-Coast trashes Rip Deal due to net damage.
0-Coast spends  to draw a card.
0-Coast spends  to draw a card.
0-Coast is ending their turn 12 with 0  and 3 cards in their Grip.
vincentkbl started their turn 13 with 2  and 1 cards in HQ.
vincentkbl uses Marilyn Campaign to gain 2 .
vincentkbl uses Daily Business Show to draw additional cards.
vincentkbl uses Daily Business Show to add 1 card to the bottom of R&D.
vincentkbl uses Turtlebacks to gain 1 .
vincentkbl uses Turtlebacks to gain 1 .
vincentkbl spends  to install a card in Server 17 (new remote).
vincentkbl spends  to draw a card.
vincentkbl spends  to gain 1 .
vincentkbl is ending their turn 13 with 7  and 2 cards in HQ.
!0-Coast uses a command: /close-prompt
0-Coast started their turn 13 with 0  and 3 cards in their Grip.
0-Coast uses Beth Kilrain-Chang to gain 1 .
0-Coast uses Aesop's Pawnshop to trash Harbinger and gain 3 .
0-Coast spends  to play Diesel.
0-Coast uses Diesel to draw 3 cards.
0-Coast spends  to draw a card.
0-Coast spends  to gain 1 .
0-Coast spends  and 5  to play Sure Gamble.
0-Coast uses Sure Gamble to gain 9 .
0-Coast is ending their turn 13 with 9  and 5 cards in their Grip.
vincentkbl rezzes Mental Health Clinic.
vincentkbl started their turn 14 with 7  and 2 cards in HQ.
vincentkbl uses Mental Health Clinic to gain 1 .
vincentkbl uses Marilyn Campaign to gain 2 .
vincentkbl uses Daily Business Show to draw additional cards.
vincentkbl uses Daily Business Show to add 1 card to the bottom of R&D.
vincentkbl uses Turtlebacks to gain 1 .
vincentkbl uses Turtlebacks to gain 1 .
vincentkbl spends  to install a card in Server 18 (new remote).
vincentkbl spends  to draw a card.
vincentkbl uses Turtlebacks to gain 1 .
vincentkbl uses Turtlebacks to gain 1 .
vincentkbl spends  to install a card in Server 19 (new remote).
vincentkbl is ending their turn 14 with 14  and 2 cards in HQ.
!0-Coast uses a command: /close-prompt
0-Coast started their turn 14 with 9  and 5 cards in their Grip.
0-Coast uses Beth Kilrain-Chang to draw 1 card.
0-Coast uses Aesop's Pawnshop to trash Harbinger and gain 3 .
0-Coast spends  to make a run on HQ.
vincentkbl has no further action.
vincentkbl wants to act before the run is successful.
vincentkbl
vincentkbl
dang
0-Coast accesses Anansi from HQ.
0-Coast spends  to make a run on Server 18.
vincentkbl has no further action.
vincentkbl wants to act before the run is successful.
0-Coast accesses Rashida Jaheem from Server 18.
vincentkbl
vincentkbl
dang
0-Coast pays 1 to trash Rashida Jaheem from Server 18.
vincentkbl uses Hostile Infrastructure to do 1 net damage.
0-Coast trashes Aesop's Pawnshop due to net damage.
0-Coast spends  to make a run on Server 19.
vincentkbl spends 2  to rez Marilyn Campaign.
vincentkbl has no further action.
0-Coast accesses Marilyn Campaign from Server 19.
0-Coast spends  and 3  to install Daily Casts.
0-Coast uses Hayley Kaplan: Universal Scholar to install Daily Casts.
0-Coast spends 3  to install Daily Casts.
0-Coast is ending their turn 14 with 5  and 3 cards in their Grip.
vincentkbl started their turn 15 with 12  and 2 cards in HQ.
vincentkbl uses Marilyn Campaign to gain 2 .
vincentkbl uses Mental Health Clinic to gain 1 .
vincentkbl uses Marilyn Campaign to gain 2 .
vincentkbl uses Marilyn Campaign to shuffle it back into R&D.
vincentkbl uses Daily Business Show to draw additional cards.
vincentkbl reveals that they drew Kakugo.
vincentkbl installs ICE protecting Server 4.
vincentkbl uses Daily Business Show to add 1 card to the bottom of R&D.
vincentkbl spends  to draw a card.
vincentkbl spends  to draw a card.
vincentkbl spends  to draw a card.
vincentkbl is ending their turn 15 with 17  and 5 cards in HQ.

**Comment by Saintis** [comment] 2018-06-09 11:06
Might be related to Marilyn campaign

**Comment by jwarwick** [comment] 2018-06-09 11:42
Or `Daily Business Show` #3599

**Comment by jwarwick** [comment] 2018-06-09 16:33
I have a fix for #3599. This is a duplicate of that bug.

**Closed by jwarwick** 2018-06-09 16:33 UTC
Labels: duplicate
