### ISSUE TITLE
Space camp access on R&D fires/prompt twice.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2720] opened 2017-08-26 03:34 UTC
Space camp fires twice and runner gets prompted twice for a successful run. Had Temujin and desperado installed. It prompts successful run twice and space camp accessed twice. First time didn't trash, then nothing happens. But run didn't end. Suddenly the successful run or jackout window prompt pops up. So I click successful run. Not again!

vincentkbl started their turn 5 with 27  and 5 cards in their Grip.
vincentkbl spends  to draw a card.
vincentkbl spends  to make a run on R&D.
micahwedemeyer has no further action.
vincentkbl uses Temüjin Contract to gain 4 .
vincentkbl uses Desperado to gain 1 .
vincentkbl accesses an unseen card from R&D.
vincentkbl pays 3  to trash Satellite Grid from R&D.
vincentkbl spends  to make a run on R&D.
micahwedemeyer has no further action.
vincentkbl uses Temüjin Contract to gain 4 .
vincentkbl uses Desperado to gain 1 .
vincentkbl accesses an unseen card from R&D.
vincentkbl uses Desperado to gain 1 .
vincentkbl accesses an unseen card from R&D.
micahwedemeyer uses Space Camp to place 1 advancement token on Ice Wall protecting HQ at position 0.
micahwedemeyer uses Space Camp to place 1 advancement token on a card in Server 1.
vincentkbl pays 3  to trash Space Camp from R&D.

vincentkbl
only one token

**Comment by JoelCFC25** [comment] 2017-08-26 13:43
Duplicate of #2348. Fix pending.

**Closed by JoelCFC25** 2017-08-26 13:43 UTC
