### ISSUE TITLE
Bad publicity and psi games

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2390] opened 2017-02-23 23:33 UTC
future perfect on R&D and corp has 1 bad publicity. Runner has 4 credits, thus 5 for the run. Bidding 1 on the TFP took runner down to 3 credits despite having the bad pub credit to spend.

**Comment by danhut** [comment] 2017-02-23 23:43
Seems like a duplicate of #2374

**Closed** 2017-03-05 13:26 UTC
Labels: bug, duplicate
