### ISSUE TITLE
Friend cannot make an account "Passwords do not Match"

### ISSUE THREAD

**Issue by ApemanB** [mtgred/netrunner#5071] opened 2020-05-02 15:12 UTC
Hello,

My friend tried to make an account yesterday (as I was hyping up the best card game ever made) and logged onto my Jinteki account without issue. However, my friend was not able to create an account getting an error that was saying "passwords do not match". He tried for about a half hour and even looked at the source code of the site trying to figure out what the issue was. Not sure what the issue is, but if there is a fix or if we did something wrong please let me know.

Thank you!

**Comment by NoahTheDuke** [comment] 2020-05-02 15:46
Thanks for the report! Duplicate of #5067

**Closed by NoahTheDuke** 2020-05-02 15:46 UTC
