### ISSUE TITLE
Reaver + Casting Call

### ISSUE THREAD

**Issue by agileminor** [mtgred/netrunner#2301] opened 2017-01-08 16:21 UTC
I've got Reaver out. Corp has Casting Call installed on an agenda. I run and steal the agenda, taking the two tags. Casting Call goes in the trash and Reaver gives me a card draw.

I don't think that is correct, because Casting Call is not an installed card, it's a "hosted condition counter" at that point.

**Comment by JoelCFC25** [comment] 2017-01-08 17:12
It's possible this could be fixed by adding a `:hosted-lost` ability to Casting Call.

**Comment by nealterrell** [comment] 2017-01-08 21:30
Unfortunately that event is when a card you were hosting is lost, but Casting Call is not hosting anything.

**Comment by jbrz** [comment] 2017-01-10 17:09
Reaver is wonky with a bunch of stuff - mainly due to poor start/end of turn triggers.  If your oppo hits `end turn` before you finish popping clone chip, smc, hopper, etc. to trigger reaver on _their_ turn, gamestate thinks you've triggered reaver on your turn, so when you hit `start` turn and use another trash ability (Aesops) at the _true_ start of turn, you don't get another card.

Probably easier to just update reaver, but there are other cards affected similarly - probably requires some optimization of start/end turn triggers

**Comment by JoelCFC25** [comment] 2017-01-10 17:38
Issue #696 is where you can find the sad history of the "I need to do stuff before your actual end of turn to do "once per turn" things" feature and its eventual rollback.

**Comment by jbrz** [comment] 2017-01-10 17:42
:D <3 One of these days I'll learn clojure and help, I promise...

**Comment by JoelCFC25** [comment] 2017-01-10 17:46
Sorry, incomplete history there--#1337 was where the feature was added.

**Comment by danhut** [comment] 2017-03-17 12:26
I cannot reproduce this at all.  Assume it got fixed via another issue.

**Comment by JoelCFC25** [comment] 2017-04-21 02:01
Agreed, no longer happening.

**Closed by JoelCFC25** 2017-04-21 02:01 UTC
Labels: bug, cards
