### ISSUE TITLE
Apparently we can't trash Jarogniew mercs anymore

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#7825] opened 2024-10-17 01:23 UTC
Needs to be done manually

**Comment by heyshiloh** [comment] 2024-10-21 19:02
```(and (= side :corp)
           (untrashable-while-resources? card)
           (> (count (filter resource? (all-active-installed state :runner))) 1))
      (do (enforce-msg state card "cannot be trashed while there are other resources installed")
          (effect-completed state side eid))```
          
          Also in its current state if you try to trash it, system will say you cant but it will consume the click anyway

**Comment by heyshiloh** [comment] 2024-10-21 19:40
So this interaction comes from the function `prevent-trash` which is a condition in `trash-resource`

the logic in the basic action to trash is actually flipped

here is how i would read this out

```
;; in order for the target card to be trashed using the basic action
(req
    ;; the following must be true
    (and
           ;; if the list of installed resources includes an "untrashable while resources card" and there is more than one resource
           (if (and (->> (all-active-installed state :runner)
                                  (filter (fn [c] (untrashable-while-resources? c)))
                                   (seq))
                          (< 1 (->> (all-active-installed state :runner)
                                  (filter resource?)
                                   count)))
                   ;; proceed
                   true
                   ;; otherwise proceed if the target card does not have the above mentioned flag
                   (not (untrashable-while-resources? target)))
            ;; it also must be a resource
           (resource? target)
           ;; it also must meet additional costs
           (...meets additional costs....)
```

The issue is that we are currently proceeding to the next checks for untrashable cards (and susequently allowing it as a choice) when there is more than one resource, but not when there is only one resource

because of this, we are getting through and allowing the following interaction to occur

<img width="268" alt="Screenshot 2024-10-21 at 12 35 16 PM" src="https://github.com/user-attachments/assets/39f29e61-2c6f-4057-bc22-b44f8601fb24">


The designation of this card is actually that it should only be a choice if the opposite is true

```
;; if the target card has the flag "untrashable while resources card" and there are less than 2 resources installed
(if (and (untrashable-while-resources? target)
      (< (count (filter resource? (all-active-installed state :runner))) 2))
;; proceed
true
;; otherwise proceed if the target does not have this flag
(not (untrashable-while-resources? target)))
```

keeping the prevent-trash-impl code intact would be important to resolving non basic action related cards, but that does leave the fact that we would lose the system warning message in the process of fixing this issue

**Comment by heyshiloh** [comment] 2024-10-21 19:42
<img width="272" alt="Screenshot 2024-10-21 at 12 42 27 PM" src="https://github.com/user-attachments/assets/e1041537-dfd6-483a-b58f-f05fdfa818ae">

**Comment by NBKelly** [comment] 2024-10-21 19:46
Neat. I know I assigned myself for this one, but feel free to make a PR anyway (I'm distracted with some other stuff right now).

**Comment by NBKelly** [comment] 2024-10-21 20:17
No worries. Any work I don't have to do is good, and the more people working on netrunner the better it will be :joy:

**Closed** 2024-10-29 16:06 UTC
