### ISSUE TITLE
Wake up call allowed to be played after a Maw trashed

### ISSUE THREAD

**Issue by yads** [mtgred/netrunner#3241] opened 2018-03-28 19:53 UTC
Runner ran the previous turn and forced a Maw trash, that was the only interaction with the Corp. Corp was able to play Wake Up Call the following turn.

Looking at the code, does it trigger if the runner trashed their own cards (e.g. Daily Casts)?

**Comment by jwarwick** [comment] 2018-03-28 21:03
Maybe fixed by #3187? It's the inverse problem I think.

**Comment by NoahTheDuke** [comment] 2018-03-28 21:43
Yeah. `(trash state side eid chosen nil)` should probably say `:corp`

**Comment by NoahTheDuke** [comment] 2018-03-29 16:27
I can't reproduce this on my local machine. Neither Maw trash, nor Daily Casts trash, nor both happening on the same turn let me play Wake Up Call. But trashing an asset did let me play Wake Up Call.

**Closed** 2019-09-01 17:57 UTC
Labels: can't reproduce
