### ISSUE TITLE
Can't Play Cards

### ISSUE THREAD

**Issue by anarchomushroom** [mtgred/netrunner#7593] opened 2024-07-29 09:53 UTC
Link to bug replay: https://jinteki.net/bug-report/bd60ba1b-3129-4fde-a442-be4ac5dc79ab?b=0

Description:

Publicly burning a smurf for this fml

Played a game, all going fairly fine, and then I untapped and couldn't play any cards. I was able to take basic actions (click for cred, draw, make a run, etc) but I wasn't able to play any of the cards in my hand, nor could I take any credits from installed cards. Pure basic action-runner

**Comment by NoahTheDuke** [comment] 2024-07-29 11:29
@NBKelly you wrote the recent "prevent misplays" code. is this related? any ideas?

**Comment by NBKelly** [comment] 2024-07-29 19:58
Probably related, but I can't see that replay.

**Comment by NBKelly** [comment] 2024-07-30 03:36
I'm not sure what the actual solution is, but what's happening is that some prompt is lingering in the state when it shouldn't be (the only other example I have, this was caused by closing some prompts during a run).
Until I properly figure out what's going on, you can clear it during your turn (when you can't play cards) by just doing another /close-prompt (even though no prompt is visible). This makes the cards playable (or at least it did in my sample case).

**Closed** 2024-07-30 19:54 UTC
