### ISSUE TITLE
Gang sign lets/forces runner to access installed upgrades in root of HQ.

### ISSUE THREAD

**Issue by xdfubar** [mtgred/netrunner#2113] opened 2016-10-21 02:13 UTC
Runner accessed two cards from hand, then accessed installed Prisec in HQ. Unsure whether this was part of the first or second gang sign access and whether or not a popup came up for the runner to access installed upgrade.

**Comment by JoelCFC25** [comment] 2016-10-21 20:10
So far I can't reproduce this. Not sure if the things being fixed in #2064 are at play here. Was the Prisec installed in the root of HQ rezzed or unrezzed at the time of the agenda score?

**Comment by xdfubar** [comment] 2016-10-23 22:04
Prisec was unrezzed.

**Comment by hwangman** [comment] 2016-10-28 21:55
Just had it happen to me in a game. Runner was Leela and had 2 Gang Signs installed. I had Crisium Grid installed in the root of HQ. When I scored an agenda, the runner was able to access cards from my hand and the installed Crisium.

**Comment by JoelCFC25** [comment] 2016-10-29 14:45
Thanks for the reproduction steps, I've now confirmed it.

**Comment by JoelCFC25** [comment] 2016-10-29 14:49
The `access-helper-hq` function has changed significantly since Gang Sign. Either it needs to be changed to provide a way of accessing only from HQ and not the contents of the root, or Gang Sign and Raymond Flint (the other card that will have this identical problem) need to be changed.

**Comment by nealterrell** [comment] 2016-10-30 17:35
@JoelCFC25, I think I can handle this.

**Comment by tscholiadis** [comment] 2016-11-02 14:29
Hi I can confirm this bug, along with a follow-up.

I am playing Leela and had 2 Gang Signs and a Logos (bug also appears with a single Gang Sign). Corp scores and Agenda and it displays the Prompt, allowing me to choose from
- Gang Sign
- Gang Sign
- Logos
- Leela's ID

When I select Gang Sign it displays the prompt
- Card from Hand
- Unrezzed Upgrade in HQ

When I select the Card from Hand, I have to select the Unrezzed Upgrade before I can continue, which is not how the card works.

As a workaround, I tried the /close-prompt command, assuming that it would close the prompt asking me to access the Unrezzed Upgrade, and taking me to the 1st prompt to access the other Gang Sign, Logos and Leela's ID. Instead, it closed ALL the prompts and would not let the Corp continue as it said "Waiting on Runner to complete action". Even giving myself clicks as a Runner and playing a Run Event card (hoping it will kick the programming to the next section) it would not allow the Corp to play.

Hope this helps and please let me know if you need further info. I can replicate this if need be in a game, as it has happened to me plenty of times.

**Comment by JoelCFC25** [comment] 2016-11-02 15:31
The fix is pending at #2131.

**Comment by nealterrell** [comment] 2016-11-02 17:07
@tscholiadis Thank you for the thorough report, it is much appreciated -- but as Joel said, we have a fix for this ready to go :).

**Comment by tscholiadis** [comment] 2016-11-02 22:23
Excellent news. I made the post mainly so that you can see that there was a follow up bug with the /close-prompt command, which may or may not be related.

Keep up the good work guys

**Closed** 2016-11-03 01:48 UTC
Labels: bug, cards
