### ISSUE TITLE
Ruhr valley not allowing run on server

### ISSUE THREAD

**Issue by Davus1988** [mtgred/netrunner#2719] opened 2017-08-25 18:06 UTC
Had an issue in a game where the runner was unable to run on a remote server with a rezzed Ruhr Valley unless they had all 4 clicks available. Thought it might be some problem with an interatction with Load Testing, but the problem persisted on turns when no Load Testing was played - the server wasn't appearing as an option to run as soon as the runner went below 4 clicks. Adding the clicks on manually didn't resolve the issue.
Thanks

**Comment by JoelCFC25** [comment] 2017-08-25 18:15
This is a duplicate of #2109.

**Closed by JoelCFC25** 2017-08-25 18:15 UTC
Labels: bug, cards, duplicate
