### ISSUE TITLE
Tag avoidance overrides other penalty options from Corp effects

### ISSUE THREAD

**Issue by tankbard** [mtgred/netrunner#1044] opened 2015-12-27 19:54 UTC
Steps to reproduce:
1. Runner has New Angeles City Hall (tag avoidance in general?)
2. Corp plays Cerebral Cast and wins the psi game (or any other effect where the Runner can choose to take tags or suffer some other negative effect? e.g. News Team)

Expected:
Runner is asked to resolve which penalty they take from step 2. If they choose the tags, they are asked if they want to trigger their tag avoidance from step 1.

Actual:
Runner is asked whether they want to trigger tag avoidance from step 1. If "No" (since they want the non-tag effect from step 2), they get the tags and never get to choose the other effect from step 2.

**Comment by JoelCFC25** [comment] 2015-12-27 20:04
Thanks for the report. I'm not sure I'm following this one yet--in testing, if I have NACH installed and have the Corp play Cerebral Cast, the Runner first sees the prompt asking if they want 1 tag or 1 brain damage. Then choosing 1 tag brings up the "Avoid any of the 1 tags?" prompt. Isn't that correct?

So you're saying somehow you got asked to avoid tags before you'd even chosen the "take 1 tag" option?

**Comment by tankbard** [comment] 2015-12-27 20:17
Well, I'll go back and see if I can get it to happen. This is from a couple days ago so maybe it got resolved? I distinctly remember preferring the brain damage since I didn't want the tag on the Corp's turn and needed to keep the money I would have used to dodge it.

**Comment by JoelCFC25** [comment] 2015-12-27 21:50
I also tried running into a News Team just now with NACH installed. I was prompted to choose between the 2 tags or "add to score area" first, then asked if I wanted to trash News Team, then got the prompt about avoiding tags--all of that seems to work correctly.

**Comment by JoelCFC25** [comment] 2016-01-07 16:40
@tankbard: When you get a chance, can you try this interaction again and see if it's working for you now? A bunch of updates have been merged and the server has been restarted.

**Comment by JoelCFC25** [comment] 2016-01-14 14:18
Closing this for now since I can't reproduce it. If it flares up again and you can reliably repeat it, please add a comment here and we'll reopen it!

**Closed by JoelCFC25** 2016-01-14 14:18 UTC
Labels: can't reproduce
