### ISSUE TITLE
Flip Switch does not work

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4137] opened 2019-03-20 22:43 UTC
All i get is this weird pop-up when i try to use it. Nothing else.
![image](https://user-images.githubusercontent.com/1651150/54724071-e78df400-4b69-11e9-9f4f-94b66fd0d6ed.png)

**Comment by NoahTheDuke** [comment] 2019-03-20 23:01
Duplicate of #4086

**Closed** 2019-03-28 14:50 UTC
Labels: duplicate
