### ISSUE TITLE
R&D Interface- Cannot add via Add Card Tool

### ISSUE THREAD

**Issue by 4716** [mtgred/netrunner#60] opened 2015-01-16 02:10 UTC
Cannot add the card R&D Interface to my runner deck. No matter how you type in the card and click it, then click add card, it does not add. I can add it through the decklist, however not through add card tool.

**Comment by mtgred** [comment] 2015-01-16 02:16
What browser (including version) and operating system do you use?

**Comment by 4716** [comment] 2015-01-16 02:27
Chrome Version 39.0.2171.95 m

Windows 7

**Comment by CptHilts** [comment] 2015-01-16 17:41
try searching "interface". I had the same issue, I think the issue is with the "&"

**Comment by 4716** [comment] 2015-01-16 17:47
I've tried that, and it still doesn't work that way for me. Only way it adds is by manually adding it to the list.

Sent from Windows Phone

-----Original Message-----

**Comment by mtgred** [comment] 2015-01-19 01:58
I did some tests on Windows 7 with Chrome 39 and it works fine. On the same machine with Firefox it would sometime bugs and sometime works. When the issue happens in Firefox, "R&amp;D Interface" would appear in the input box. Replacing the "&amp;" with just "&" won't fix the issue. But when it did work "R&D Interface" would appear correctly when choosing the card in the menu.

I'm not sure what's causing the issue and will investigate later on. In meanwhile you will have to add it through the deck list.

**Comment by Saintis** [comment] 2015-12-30 18:15
Tested on Chrome and Safari on Mac. Can this still be reproduced?

**Comment by JoelCFC25** [comment] 2015-12-31 21:47
Definitely still a problem on the PC side. Chrome in Windows 7 shown below (hitting Add to deck yields no effect): 

![image](https://cloud.githubusercontent.com/assets/10407969/12068531/b3d337a2-afd5-11e5-9f45-ba9b0363c296.png)

**Comment by 4716** [comment] 2015-12-31 22:13
I think you got an answer from someone else that it was still an issue on windows 7 with chrome.

 I got busy at work and forgot to finish answering you. I have not checked recently so honestly do not know, but I can check if you need me too tonight.

Thanks!
Corey


Sent from Windows Phone

-----Original Message-----

**Comment by queueseven** [comment] 2016-04-19 07:32
No problem for me with Windows 8 and Chrome 50. @JoelCFC25 / @4716  can you still reproduce this? If not, let's close this issue.

**Comment by zaroth** [comment] 2016-04-19 08:18
Probably an update in React fixed this. I am able to add RDI on latest Firefox via this textbox, couldn't before. I think it very well may be fixed :+1:

**Comment by zaroth** [comment] 2016-04-19 08:26
@queueseven: I just tested it a bit more and can provide more info. Two cases, both behave differently:

- I type "R&D" in the box, it suggests R&D interface, I click it, it adds normally.
- I type "interface" in the box, it suggests a few interfaces, I click R&D interface, it adds bugged out with `&amp;` - as described by @JoelCFC25.

**Comment by queueseven** [comment] 2016-04-19 09:04
Ah, great find. The issue is clicking "R&D Interface" with the mouse in the dropdown, then.

I can also reproduce this. 

I usually select the card with <kbd>UP</kbd>/<kbd>DOWN</kbd> and press <kbd>Enter</kbd>.

**Closed** 2016-04-28 21:55 UTC
Labels: bug, deckbuilder
