### ISSUE TITLE
Archangel/The Turning Wheel multi-access bug

### ISSUE THREAD

**Issue by otterstrike** [mtgred/netrunner#2040] opened 2016-10-03 21:34 UTC
Not sure if this applies to all multi-access cards, but when accessing Archangel as the first card in RnD with multiple accesses via TTW, the second and third accessess where all Archangel, despite their only being two available to access in the deck. Archangel was not fired in this circumstance. Game finished at 2:31 PST, otterstrike.

**Comment by zaroth** [comment] 2016-10-03 21:45
Duplicate of #2038.

**Closed by zaroth** 2016-10-03 21:45 UTC
