### ISSUE TITLE
Return to active game after active tab is closed (browser crash, close tab by accident etc.)

### ISSUE THREAD

**Issue by sars1492** [mtgred/netrunner#2069] opened 2016-10-09 08:19 UTC
Is possible to return to certain game as player (protected by password) after browser crash, computer crash, tab with game is closed by accident, etc?

**Comment by Saintis** [comment] 2016-10-09 15:15
Duplicate of #418 perhaps.

**Closed** 2016-10-09 15:18 UTC
Labels: duplicate
