### ISSUE TITLE
Hyoubu Institute ID reveal bug

### ISSUE THREAD

**Issue by HongkongKoma** [mtgred/netrunner#4126] opened 2019-03-20 10:01 UTC
When using the Hyoubu ability to reveal a runner's card, I get an encoded message:
<img width="373" alt="Bildschirmfoto 2019-03-20 um 10 27 14" src="https://user-images.githubusercontent.com/11632063/54675753-70237a80-4aff-11e9-9c76-669588b99955.png">
(sry for cutting the image, chat scrolled away too far).

**Comment by Saintis** [comment] 2019-03-20 10:14
Duplicate of  #4082, supposedly fixed by #4087... Has that change been deployed yet @NoahTheDuke?

**Comment by HongkongKoma** [comment] 2019-03-20 10:21
Sorry, I searched if there is a similar post but did not find it.

**Comment by Saintis** [comment] 2019-03-20 10:27
No worries, the other post has a hard-to-spot title.

**Comment by NoahTheDuke** [comment] 2019-03-20 11:54
I don’t believe a fix has been deployed. I hope to wrap up enough fixes that we can deploy later this week

**Closed** 2019-03-20 13:26 UTC
Labels: bug, cards, duplicate
