### ISSUE TITLE
What happened to Run Event graphics?

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#4528] opened 2019-09-28 16:57 UTC
I am finding it incredibly difficult to notice when the runner is playing run events.  Yes, there is the notification in the log, and the appearance of the card in the heap, but I really appreciated the card appearing on top of the arrow that signifies which server is being run.  What happened to it?

**Comment by NoahTheDuke** [comment] 2019-09-28 23:43
This is a duplicate of #4521, and is fixed by #4522

**Closed by NoahTheDuke** 2019-09-28 23:43 UTC
