### ISSUE TITLE
UI Improvement - Removed from Game consolidation

### ISSUE THREAD

**Issue by karmaportrait** [mtgred/netrunner#2151] opened 2016-11-07 00:17 UTC
Multiple 'Removed from the game' cards can stack, creating clutter.

see [this situation](https://i.imgur.com/cy8w4QT.png)

**Comment by nealterrell** [comment] 2016-11-07 01:25
What's the second card?

**Comment by karmaportrait** [comment] 2016-11-07 01:47
Net Celebrity

**Comment by nealterrell** [comment] 2016-11-08 00:54
It looks like Fan Site to me, actually. Anyways, excepting unreproducible UI issues, there are only two RFG zones in the game/UI, one for each player. If a Corp uses multiple Jackson Howards, they will all go into the same RFG zone. If a Runner is hit with Chronos Project, all their cards will go to their single RFG zone. The only time two RFG zones are shown is when each player has forfeited cards. Did the Fansite somehow make its way to the Corp's control, maybe via Exchange of Information?

**Comment by karmaportrait** [comment] 2016-11-08 03:54
Fan Site was runner sacrifice, never under Corp's control. So not sure if this was a rando bug or what. Can probably close this. Thanks for the attention to the "issue". :)

**Comment by artturipi** [comment] 2016-11-24 20:28
It does seem to me that Fan Site when forfeited with Artist Colony at least goes to the corp's RFG zone.

**Comment by JoelCFC25** [comment] 2016-11-25 19:52
When a card uses `:forfeit` in its cost vector, the `forfeit` function is hard-coded to move the forfeited item to `[:corp :rfg]`. Currently Artist Colony, Data Dealer, and Liberated Chela are the only Runner cards that forfeit cards this way. Hyperdriver, Trope, and other Runner cards that remove themselves from the game do so with the `move` function, thus ending up in `[:runner :rfg]`.

**Comment by Saintis** [comment] 2017-05-28 22:22
So fix for this would be to have `forfeit` move the card to the `:side` that matches the player paying the cost yeah?

**Closed** 2017-08-26 14:43 UTC
Labels: game interface
