### ISSUE TITLE
Feature: Add 'alert' button

### ISSUE THREAD

**Issue by erithtotl** [mtgred/netrunner#1431] opened 2016-04-06 22:11 UTC
Add a button that allows a player to flash an alert/interrupt message on the screen when they'd like to react during a timing window.  This wont actually halt the game, but will just make an obvious, screen centered message as often players don't see the chat window, or it takes too long to type a message there when you need the other player to pause.

Pardon if this is a duplicate I couldn't find another request like this.

**Comment by zaroth** [comment] 2016-04-06 22:14
Duplicate of #1348 (involving pause) and #332 (sending quick messages to other player without a pause).

**Closed by zaroth** 2016-04-06 22:14 UTC
