### ISSUE TITLE
Laramy Fisk and Temujin Contract

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#1968] opened 2016-09-17 01:24 UTC
Hi, I couldn't find this bug anywhere already.

When you play Laramy Fisk and make a Temujin Contract run weird things happen! Most commonly, putting Temujin on a central server leads to the first lot of money happening fine (whether you choose to trigger Fisk or Temujin first), but then on the second and subsequent runs Temujin doesn't trigger *and* the server designation on the Temujin card (the orange box saying HQ, R&D or what have you) disappears. On some occasions though, the money *does* come off for the second Temujin run, but the money stays at 16 on the card (should now be 12) and the server designation still disappears

I think it might be a symptom of something getting tangled up by Laramy, since after Temujin goes haywire all sorts of weird successful run triggers tend to start happening like successful remote runs giving a choice list of triggering Sec Test (not on that server), Temujin (not on that server) or Laramy Fisk (obviously not on a remote), none of which actually resolve but shouldn't be trying to trigger at all. Or the same thing happening on the central servers when Laramy Fisk has already triggered once already so shouldn't be triggering again.

Hope that helps!

**Comment by JoelCFC25** [comment] 2016-09-17 01:33
Thanks--confirmed the problem. This looks like a job for @nealterrell!

**Comment by HubGitAccoutn** [comment] 2016-09-21 04:07
Just an addition in case it helps diagnose the problem at all: in a recent game I ran Archives (triggering Laramy Fisk), *then* installed Temujin on Archives and ran it twice afterwards. In this case, with the Fisk trigger having happened already that turn there was no bugginess, no extra prompts, and the turn ended with Temujin correctly on 12 credits and still highlighted as pointing at Archives. However the next turn, running Archives again (triggering Fisk) led to the usual bug in removing the server designation from Temujin. The four credits were automatically gained, but rather than the remaining credit pool on Temujin reducing to 8, or even staying put on 12, they actually went back up to 16 again.

**Comment by unitled** [comment] 2016-09-21 14:00
Just to note, I'm having this problem with Sil as well, especially when combined with Sec Testing; the Temujin 'falls off' the targetted server and I have to continue manually.

When I use Temujin with her it seems to ask on ANY run whether I want to trigger her ability or Temujin, but doesn't do either when I click.

**Comment by nealterrell** [comment] 2016-09-21 18:27
I'll take a look.

**Comment by nealterrell** [comment] 2016-09-21 18:57
Can anyone confirm that this only happens if there are at least THREE "when a run is successful" cards involved? (Example: Fisk, Temujin, and SecTest all installed)

**Comment by JoelCFC25** [comment] 2016-09-21 19:31
I am getting it in the most minimal case--Temujin targeting HQ, run HQ with Silhouette. After resolving both, the label is gone from Temujin and it won't pay out for HQ runs anymore.

**Comment by nealterrell** [comment] 2016-09-22 19:03
Aite, found and fixed. Thanks everyone.

**Comment by nealterrell** [comment] 2016-09-22 19:17
As an explanation, this bug happens with any other card that forces a sucessful-run simultaneous trigger prompt. Fisk and Silhouette are two examples, but so is Equivocation and I'm sure many others. The bug is also not just on Temujin, but also Security Testing, Patron, and many others. The bug only happens if Temujin/etc is **not** the last card to be resolved in the simultaneous trigger prompt. Until a fix goes live, you should be able to avoid the issue by choosing Temujin to resolve first. (This unfortunately does not work for a SecTest + Temujin run, because you will not get the prompt to choose a resolution order, so one of the two will definitely be last to resolve).

**Closed** 2016-09-27 16:19 UTC
Labels: bug, cards
