### ISSUE TITLE
Makler gains a credit after Konjin psi game

### ISSUE THREAD

**Issue by aenimosity** [mtgred/netrunner#5031] opened 2020-04-04 12:56 UTC
Encountered Konjin with Makler installed. Runner and Corp both pay 1. Makler gained 1 credit.

**Comment by NoahTheDuke** [comment] 2020-04-08 00:07
Thanks for the report!

**Comment by NoahTheDuke** [comment] 2020-04-08 00:28
I can't reproduce this. Next time it happens, can you snap a screenshot?

**Comment by francescopellegrini** [comment] 2023-01-02 15:31
Might as well close this.

**Closed** 2023-01-02 16:17 UTC
Labels: bug, can't reproduce, card, engine
