### ISSUE TITLE
DaVinchi trash error?

### ISSUE THREAD

**Issue by Trackrise** [mtgred/netrunner#2118] opened 2016-10-22 21:08 UTC
Please describe the circumstances of your error here.
I was discarding down to 7, which I've had to do before, but when I tried to trash DaVinci, it broke the game. Don't know whether or not DaVinci was the cause or not. I told my opponent to just hit me for net damage so we could move on.

Stack Trace:

``` clojure
Error do move DaVinci #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Numbers ops "Numbers.java" 1013]}]
 :trace
 [[clojure.lang.Numbers ops "Numbers.java" 1013]
  [clojure.lang.Numbers gt "Numbers.java" 229]
  [game.core$has_most_faction_QMARK_$reducer__15817 invoke "identities.clj" 19]
  [clojure.lang.PersistentArrayMap kvreduce "PersistentArrayMap.java" 373]
  [clojure.core$fn__6945 invokeStatic "core.clj" 6562]
  [clojure.core$fn__6945 invoke "core.clj" 6547]
  [clojure.core.protocols$fn__6763$G__6758__6772 invoke "protocols.clj" 174]
  [clojure.core$reduce_kv invokeStatic "core.clj" 6573]
  [clojure.core$reduce_kv invoke "core.clj" 6564]
  [game.core$has_most_faction_QMARK_ invokeStatic "identities.clj" 24]
  [game.core$has_most_faction_QMARK_ invoke "identities.clj" 9]
  [game.core$fn__16269 invokeStatic "identities.clj" 740]
  [game.core$fn__16269 invoke "identities.clj" 740]
  [game.core$trigger_event_sync_next invokeStatic "events.clj" 47]
  [game.core$trigger_event_sync_next doInvoke "events.clj" 40]
  [clojure.lang.RestFn applyTo "RestFn.java" 157]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 587]
  [game.core$trigger_event_sync invokeStatic "events.clj" 64]
  [game.core$trigger_event_sync doInvoke "events.clj" 55]
  [clojure.lang.RestFn applyTo "RestFn.java" 151]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 660]
  [game.core$resolve_trash invokeStatic "rules.clj" 303]
  [game.core$resolve_trash doInvoke "rules.clj" 299]
  [clojure.lang.RestFn invoke "RestFn.java" 500]
  [clojure.lang.AFn applyToHelper "AFn.java" 171]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 587]
  [game.core$trash invokeStatic "rules.clj" 337]
  [game.core$trash doInvoke "rules.clj" 307]
  [clojure.lang.RestFn invoke "RestFn.java" 500]
  [game.core$trash invokeStatic "rules.clj" 310]
  [game.core$trash invoke "rules.clj" 307]
  [game.core$move_card invokeStatic "actions.clj" 87]
  [game.core$move_card invoke "actions.clj" 58]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 150]
  [game.main$handle_command invoke "main.clj" 139]
  [game.main$run$fn__25311 invoke "main.clj" 185]
  [game.main$run invokeStatic "main.clj" 175]
  [game.main$run invoke "main.clj" 169]
  [game.main$_main$fn__25346 invoke "main.clj" 239]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by JoelCFC25** [comment] 2016-10-22 23:26
Thanks--looks like you were using a faction draft ID. Duplicate of #2112.

**Closed** 2016-11-06 15:54 UTC
Labels: bug, duplicate
