### ISSUE TITLE
Kingmaking offers no option on how many cards to draw

### ISSUE THREAD

**Issue by TheSovietLoveHammer** [mtgred/netrunner#7325] opened 2024-03-22 01:51 UTC
Link to bug replay: https://jinteki.net/bug-report/70bc7226-e5b4-451d-b4b7-941389f559dd?b=0

Description:

When kingmaking was scored 3 cards were automatically drawn, rather than a choice of 0, 1, 2 or 3 cards.

**Comment by NBKelly** [comment] 2024-03-22 05:16
Duplicate of #7316

**Closed** 2024-03-23 11:47 UTC
