### ISSUE TITLE
Mystic Maemi shows incorrect message when trashing from it's effect

### ISSUE THREAD

**Issue by hiddenaway1** [mtgred/netrunner#6725] opened 2022-11-23 23:26 UTC
When trashing a card from Mystic Maemi's effect, you don't see the card name but see something different instead.

![image](https://user-images.githubusercontent.com/35308609/203662867-8dfa4b53-3525-4554-9345-e6081ae37baf.png)

**Comment by francescopellegrini** [comment] 2022-12-03 08:53
I cannot reproduce it using the latest version of the code (not yet released)

**Comment by francescopellegrini** [comment] 2023-01-02 15:32
Might as well close this.

**Closed** 2023-01-02 16:16 UTC
