### ISSUE TITLE
Jak Sinclair + losing clicks ice subroutines

### ISSUE THREAD

**Issue by Dragoonkin** [mtgred/netrunner#2911] opened 2017-10-25 13:43 UTC
Jak Sinclair fires before you take clicks, which is incorrect by the current timing chart. Which means that ice subroutines that force you to lose clicks don't make you lose clicks, when they should.

Gain clicks is 1.1, and "When your turn begins" triggers are 1.4 on the timing chart. So you should have your clicks long before this fires.

**Comment by Dragoonkin** [comment] 2017-10-25 13:45
As a side note, I know this is manually-correctable behavior, I just didn't know it was incorrect 'til someone told me so. Oops accidental cheating!

**Comment by Saintis** [comment] 2017-10-25 13:46
Duplicate of #1764

**Comment by Saintis** [comment] 2017-10-25 13:47
But good bringing this back to attention, since the fix _should_ be easy...

**Comment by nealterrell** [comment] 2017-10-28 01:04
May not be an easy fix. I programmed the feature this way because having clicks turns on the Action buttons in the Runner's UI, which would allow them to trigger normal actions during the "Start of turn" ability window, when they're only supposed to focus on their start-of-turn triggers.

**Comment by danhut** [comment] 2018-04-01 22:46
Fixed via #1764

**Closed by danhut** 2018-04-01 22:46 UTC
Labels: duplicate
